### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by cmkcmk181** [go-chassis/go-chassis#1006]
go get github.com/go-chassis/go-chassis/v2报错如下：

![image](https://user-images.githubusercontent.com/8915324/133206364-b297f639-a386-443e-824c-dbabaf71a5ac.png)

go:1.17

**Comment by tianxiaoliang** [comment]
go get github.com/go-chassis/go-chassis/v2@v2.3.0

**Comment by tianxiaoliang** [comment]
看错误像是windows os的syscall兼容性问题，但是go chassis对操作系统没有限制啊

**Comment by tianxiaoliang** [comment]
使用go 1.17尝试了go get，过程很顺利
https://golang.org/dl/go1.17.1.windows-amd64.msi

**Comment by cmkcmk181** [comment]
重装了下go好了
