### ISSUE TITLE
REST Write 性能下降严重

### ISSUE THREAD

**Issue by cmkcmk181** [go-chassis/go-chassis#1007]
go-chassis：v2.3.0
go:v1.17.1

在使用Write方法时性能下降严重：
不使用Write时性能如下：
func (r *RestFulHello) SayHello(b *rf.Context) {
	fmt.Println("OK")
}
![image](https://user-images.githubusercontent.com/8915324/133734455-b46a302a-dc70-487d-b3ad-87003c10718a.png)

使用Write时性能如下：
func (r *RestFulHello) SayHello(b *rf.Context) {
	b.Write([]byte("get user id: " + b.ReadPathParameter("userid")))
}
![image](https://user-images.githubusercontent.com/8915324/133735338-c560df08-8cdc-4eda-92d9-0493e5eb956a.png)

**Comment by tianxiaoliang** [comment]
感谢建议，go chassis使用https://github.com/emicklei/go-restful作为底层能力，可以看下这个框架的性能下降

**Comment by cmkcmk181** [comment]
应该和go-restful框架无关，我集成gin后也是如此，但单独使用gin性能比较高。是因为使用service-center的原因？还是哪里配置不对？

**Comment by tianxiaoliang** [comment]
请提供下handler chain的配置

**Comment by tianxiaoliang** [comment]
如果没有解决问题再open吧，先关闭，看下是否是某些资源没有关闭
