### ISSUE TITLE
在 VS Code 中启动项目失败

### ISSUE THREAD

**Issue by Lwife** [go-chassis/go-chassis#1014]
在 VS Code 中编写了一个很小的 demo，然后通过 F5 运行，输出：
```go
init chassis fail: [C:\Users\Ltozv\AppData\Local\Temp\conf\chassis.yaml] file not exist.
```
但是我的当前项目目录在
```go
D:/project/workspase/go/src/go.chassis.demo
```
通过命令行执行
```cmd
$ export CHASSIS_HOME=$PWD
$ go run main.go
```
可以正常执行，若不执行 export 命令通过命令行也会执行失败。

**Comment by tianxiaoliang** [comment]
Hi，通常代码是不关心自己运行自己的具体IDE的。go chassis由于需要机遇配置文件来启动，因此需要运行前指定环境变量。它默认启动会找当前目录下的conf文件下的配置文件，也不需要配置环境变量

**Comment by Lwife** [comment]
> Hi，通常代码是不关心自己运行自己的具体IDE的。go chassis由于需要机遇配置文件来启动，因此需要运行前指定环境变量。它默认启动会找当前目录下的conf文件下的配置文件，也不需要配置环境变量

既然默认如此，为何我的项目在 D 盘项目却会去 C 盘寻找呢？
PS：我的电脑和所有环境都是新搭建的。

**Comment by tianxiaoliang** [comment]
因为你本质上运行的事go run xxx，go自己的机制，和使用什么IDE和编程框架都无关
https://github.com/golang/go/issues/8451

**Comment by Lwife** [comment]
> 因为你本质上运行的是go run xxx，go自己的机制，和使用什么IDE和编程框架都无关 [golang/go#8451](https://github.com/golang/go/issues/8451)
> 
> 又或者有些IDE会先go build，再运行二进制，这时是IDE自己规划的临时目录，不会在工作目录下留下痕迹

好的，非常感谢。

**Comment by tianxiaoliang** [comment]
> > 因为你本质上运行的是go run xxx，go自己的机制，和使用什么IDE和编程框架都无关 [golang/go#8451](https://github.com/golang/go/issues/8451)
> > 又或者有些IDE会先go build，再运行二进制，这时是IDE自己规划的临时目录，不会在工作目录下留下痕迹
> 
> 好的，非常感谢。

u r welcome, and hope you can contibute this project in near future
