### ISSUE TITLE
不同app（应用）之间的服务无法调用成

### ISSUE THREAD

**Issue by lvphpwb** [go-chassis/go-chassis#1020]
**Describe the bug**
在app为web的服务中调用app为chassis的服务接口
tag := map[string]string{"app": "chassis", "version": "1.0.2"}
resp, err := core.NewRestInvoker().ContextDo(context.TODO(), req, core.WithRouteTags(tag))

不知道是不是哪里设置有问题，服务发现找不到web对应的服务实例，是不是服务依赖过滤掉了

目前修改是在
servicecenter.go 的 FindMicroServiceInstances 方法加上：

if appID != runtime.App{
    consumerID = ""
}

**Comment by tianxiaoliang** [comment]
不同app其实应该走网关，我不建议直接走微服务的客户端负载均衡

**Comment by lvphpwb** [comment]
嗯 最好是不要这么用，只是在测试WithRouteTags这个方法的时候发现了这个问题
