### ISSUE TITLE
关于v2.3.0版本中commit 注册实例时候默认不注册schema到service-center #999 (#1000)，建议文档补充介绍该开关

### ISSUE THREAD

**Issue by whitefir** [go-chassis/go-chassis#1035]
**Describe the bug**
1. 我们的产品在升级go-chassis版本时遇到问题，从v2.1.1升级至v2.3.0，升级后服务不注册schema。
经定位，是这次合入引进的开关导致默认没有完成该动作。
**个人认为这样的开关对新服务很不友好。这种应该是影响基本功能的开关，建议补充介绍文档并在版本更新日志与Get Started里描述一下。**

2. 另外，我认为这次MR引入的servicecomb.registry.uploadSchema这样的配置项，也应该在
\github.com\go-chassis\go-chassis\v2@v2.3.0\core\config\model\registry.go里的这个结构RegistryStruct中补充一下吧。

当然也可能是我个人的理解不足，欢迎讨论。

**Version of go chassis**
问题出现是v2.1.1升级至v2.3.0，分析是v2.3.0引入

**To Reproduce**
服务在v2.1.1正常工作，升级v2.3.0，没有对chassis.yaml做变动。

附相关链接：
commit 注册实例时候默认不注册schema到service-center: 
[https://github.com/go-chassis/go-chassis/commit/3cc32f870d8d624df4d5dbebd37e546da4c3890a](https://github.com/go-chassis/go-chassis/commit/3cc32f870d8d624df4d5dbebd37e546da4c3890a)

issue 注册实例时候默认不注册schema到service-center:
[https://github.com/go-chassis/go-chassis/issues/999 ](https://github.com/go-chassis/go-chassis/issues/999 )

**Comment by tianxiaoliang** [comment]
欢迎加我的微信，深度交流tianxiaoliang2017

**Comment by tianxiaoliang** [comment]
在你提到的commit里我们加入了 文档说明
![image](https://user-images.githubusercontent.com/1610890/173589178-aed859e7-3ebc-4d36-90c4-8d886c79a3fc.png)

**Comment by hoseazhai** [comment]
v.2.4.0添加schema的文档有么

**Comment by tianxiaoliang** [comment]
> v.2.4.0添加schema的文档有么

https://go-chassis.readthedocs.io/en/v2.4.0/user-guides/registry.html

将uploadSchema改为true
