### ISSUE TITLE
Highway有出现以下错误

### ISSUE THREAD

**Issue by sxk1985** [go-chassis/go-chassis#163]
遇到highway的报错：
{"level":"DEBUG","timestamp":"2018-04-02 11:08:26.184 +08:00","file":"handler/tracing_handler.go:89","msg":"opentracing: SpanContext not found in Extract carrier"}
{"level":"ERROR","timestamp":"2018-04-02 11:08:26.185 +08:00","file":"highway/highway_msgobj.go:188","msg":"Recv Frame head  failed.","data":{"error":"EOF"}}
{"level":"ERROR","timestamp":"2018-04-02 11:08:26.185 +08:00","file":"highway/highway_msgobj.go:188","msg":"Recv Frame head  failed.","data":{"error":"EOF"}}
或者：
2018-04-03 13:40:20.220 +08:00 ERROR highway/highway_msgobj.go:188 Recv Frame head  failed. error: read tcp 127.0.0.1:8082->127.0.0.1:56483: use of closed network connection

**Comment by wangkirin** [comment]
hi @sxk1985 , thank you for your report ~~~~
we will investigate  and fix it later

**Comment by tianxiaoliang** [comment]
@sxk1985  plz check again

**Comment by tianxiaoliang** [comment]
highway is deprecated now, we have integrate with grpc. plz use grpc instead
