### ISSUE TITLE
如何在zipkin里显示有依赖关系链式调用?比如a调b,b调c

### ISSUE THREAD

**Issue by marknewmail** [go-chassis/go-chassis#258]
比如我在例子中的rest server的Sayhello中又调用了RPCServer的HelloService的SayHello方法，运行了rest client程序后，为何在zipkin里没有体现成依赖关系，而是两条独立的调用信息？
tracing配置：
  handler:
    chain:
      Provider:
        default: bizkeeper-provider,ratelimiter-provider,tracing-provider
tracing:
  enabled: true
  collectorType: zipkin
  collectorTarget: http://localhost:9411/api/v1/spans

改造后的RestFul Sayhello
//Sayhello is a method used to reply user with hello
func (r *RestFulHello) Sayhello(b *rf.Context) {
	id := b.ReadPathParameter("userid")
	log.Printf("get user id: " + id)
	b.Write([]byte(fmt.Sprintf("user %s from %d", id, num)))
	//Init framework
	// if err := chassis.Init(); err != nil {
	// 	lager.Logger.Error("Init failed.", err)
	// 	return
	// }
	//declare reply struct
	reply := &helloworld.HelloReply{}
	log.Printf("reply", reply)

	//Invoke with microservice name, schema ID and operation ID
	if err := core.NewRPCInvoker().Invoke(context.Background(), "RPCServer", "HelloService", "SayHello",
		&helloworld.HelloRequest{Name: "Peter"}, reply); err != nil {
		lager.Logger.Error("error", err)

	}
	// b.Write([]byte(fmt.Sprintf("user-rpc %s from %d", id, num)))
	lager.Logger.Info(reply.Message)
}

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/tree/master/examples/monitoring
here is an example of zipkin

**Comment by tianxiaoliang** [comment]
currently we only support http tracing, we will support RPC in future

**Comment by marknewmail** [comment]
My problem is A call B,B call C,hope to show only one record in zipkin to show linked call,but two records have been shown.And I've use the example 'monitoring' to test,use http protocol.Thanks a lot.
![image](https://user-images.githubusercontent.com/6514521/42408506-45db3506-8200-11e8-97a8-e17b1714f7e4.png)

**Comment by tianxiaoliang** [comment]
have fixed this issue and supplied new examples

**Comment by tianxiaoliang** [comment]
use that to verify
https://github.com/go-chassis/go-chassis/tree/master/examples/monitoring
