### ISSUE TITLE
tls用法是否可以更灵活一些？

### ISSUE THREAD

**Issue by zhangfeng751** [go-chassis/go-chassis#264]
**Is your feature request related to a problem? Please describe.**
tls，例如服务A作为consumer，服务B和C作为provider，B服务开启tls，C服务也开启tls，需要A服务在配置文件tls.yaml分别提前指定调用B服务用***证书，指定调用C服务使用证书***等，是否可以做个通配的证书，同时根据endpoint自动识别provider服务实例是否开启tls，开启的话就用证书文件对接，不开启tls就不用tls对接。这样灵活性更高。

**Describe the solution you'd like**
通配的证书，同时根据endpoint自动识别provider服务实例是否开启tls，开启的话就用证书文件对接，不开启tls就不用tls对接。

**Describe alternatives you've considered**

**Additional context**

**Comment by ichiro999** [comment]
go-chassis的rest client可以通过通过endpoint自动识别provider是否开启tls，若endpoint包含sslEnable=true则开启tls对接；否则通过tls.yaml来进行判断

**Comment by tianxiaoliang** [comment]
master分支已经合入，请关注后续release
