### ISSUE TITLE
This is not inspired by go-micro

### ISSUE THREAD

**Issue by asim** [go-chassis/go-chassis#28]
This is not inspired by go-micro. It's literally lifting and shifting code. I can see my actual code everywhere. Maybe come discuss how you can leverage go-micro rather than just taking code.

**Comment by tianxiaoliang** [comment]
Hi Asim, I agree about  leveraging go-micro rather than just taking code. But when I talking about inspiration, I mean the micro interface design and plugin thinking, they are great, appreciate those, 
we already change a lot of implementation of micro component like selector or changed the interface. So how about this, we have  2 folders "vendor" is for those lib we never changed and "thirt_party" is for lib we made some changes, we will put all go-micro code in there, after this you can review our code again to see if we properly deal with your code

regards

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/tree/master/core/client/client.go
https://github.com/ServiceComb/go-chassis/tree/master/core/server/server.go
https://github.com/ServiceComb/go-chassis/blob/master/core/transport/transport.go
https://github.com/ServiceComb/go-chassis/tree/master/core/loadbalance/default.go
https://github.com/ServiceComb/go-chassis/tree/master/core/loadbalance/selector.go
https://github.com/ServiceComb/go-chassis/tree/master/core/loadbalance/filter.go
https://github.com/ServiceComb/go-chassis/blob/master/core/loadbalance/strategy.go
https://github.com/ServiceComb/go-chassis/blob/master/core/loadbalance/options.go


that is all of files which come from micro, I will move them to third_party folder

**Comment by tianxiaoliang** [comment]
Hi Asim, I have changed the code, please check again, did I do well? thanks. the only word M not agree with is "everywhere". M truly sorry about not moving those files to third_party folder, my mistake

**Comment by asim** [comment]
There are many other places where you've just lifted code with no license reference. You do realise all micro projects are under the apache 2 license which means you must give credit where code is taken from there even when modified after. 

The tcp transport 
Yours: https://github.com/ServiceComb/go-chassis/blob/master/transport/tcp/tcp.go
Micro: https://github.com/micro/go-plugins/blob/master/transport/tcp/tcp.go

**Comment by asim** [comment]
The other point is. Is this an official huawei project or something separate? I would not expect this kind of behaviour from a company.

**Comment by tianxiaoliang** [comment]
As you see, there is https://github.com/ServiceComb/go-chassis/tree/master/third_party/forked/go-micro in the beginning, and I learned a lot from go-micro, I think it is great, So I also advertised this great framework in my readme. I never mean to cove the fact that we use go-micro code, but at beginning , it is an internal project in company which haven't been considered to open source, and we just use few files in your project, so we just introduced into this project and change it.  as we planed to open source , we put all libs we changed to thrid_party folder. But still there is some files we have missed. This is the result of negligence, we didn't fully check files in project.

And about leveraging go-micro, have u think about accept our changes, we can merge back to go-micro, but that means it will totally change your registry model, but you can get http protocol support and some new strategy and filter

**Comment by tianxiaoliang** [comment]
Thanks for pointing that out, go-micro is a great framework, which I learned lot of thing there. I'm really appreciate your work. 
Can you give me your email, thus we can do further disscussion in email, thanks very much.

**Comment by asim** [comment]
I don't feel the need to discuss this in any other forum except a public one here so everyone can see. 

Is this an official huawei project?

**Comment by WillemJiang** [comment]
The license and copyright of go-micro had been included at the initial commit of the go chassis here[1]. 
And now the copyright of go-micro has been added to the notice file in the ROOT directory.

[1] https://github.com/ServiceComb/go-chassis/blob/master/third_party/forked/go-micro/LICENSE

**Comment by asim** [comment]
Thank you for doing that. Although you still have not answered my question. Is this an official huawei project?

**Comment by asim** [comment]
Also note. I previously checked the repo for licenses. It was not there. This has been added after the fact and back dated.

**Comment by asim** [comment]
Please answer my question. Is this an official huawei project?

**Comment by WillemJiang** [comment]
Hi Asim，

Thanks for helping us correct the License issue to honor copyright of the original author. The go-chassis is currently a general open source project under Github but we do have plan to merge it into Apache ServiceComb (incubating), which is donated by Huawei. Is this going to be a problem for you? I'm not quite sure what your mean on Huawei official project. Can you give me some of your definition on this?

I‘m quite impressed by the pluggable design of go-micro.  go-chassis uses go-micro's client, server, selector, codec and transport modules to get the pluggability, but go-chassis has some other advanced services governance features, such as fault tolerance, circuit breaker, load balancing, monitoring,  hot reconfiguration.

Anyway, it would be fantastic if we could leverage go-micro and also contribute some of changes back to the upstream, and I am very open to any of this kind of discussion.

**Comment by asim** [comment]
> I'm not quite sure what your mean on Huawei official project
Basically what I'm saying is, are you working on this at Huawei. Is this effort being funded by Huawei. Is it being done on company time. Which in essence makes it an official project.

> go-chassis has some other advanced services governance features, such as fault tolerance, circuit breaker, load balancing, monitoring, hot reconfiguration.
These are concerns micro addresses in different ways. We have a middleware interface known as wrappers which let's extra functionality be added https://github.com/micro/go-plugins/tree/master/wrapper.  Further efforts were also made in go-os but requires a team of developers to drive forward https://github.com/micro/go-os

> Anyway, it would be fantastic if we could leverage go-micro and also contribute some of changes back to the upstream, and I am very open to any of this kind of discussion.
Contribution is welcome. Plugins are maintained in go-plugins https://github.com/micro/go-plugins. If you're building higher level functionality as you say then it appears as part of the ecosystem https://micro.mu/explore/. 

If this is an official Huawei project then it would be interesting to partner much like we've done with Sixt.

**Comment by WillemJiang** [comment]
Thanks for your great suggestions. As an open source developer,  it's a common practices that several projects work together as a community.  But it is out of my control to offer the business partnership right now, maybe we can talk about it in another thread later.

**Comment by itechbear** [comment]
I believe it is an official project. Many BIG Chinese companies (oops,I'm from China too), like Huawei, Xiaomi, etc, don't take "Open Source" serious. It's common for them to steal source code. Anyway, Huawei is doing better on this project, at least they let you know that.

**Comment by lgjabc** [comment]
I know from the zhihu....

**Comment by Liberxue** [comment]
The spirit of open source is not a plagiarism,Technology needs awe
Huawei 

> https://www.zhihu.com/question/266757429/answer/314676575

**Comment by llllll00700** [comment]
看着都脸红

**Comment by RainingNight** [comment]
any news ? :)

**Comment by OrangeHao** [comment]
They don't know what is the meaning of license.A big company,kidding me

**Comment by tianhe2018** [comment]
昨晚被刷屏了， 作为一个吃瓜群众， 引用一句话来形容这件事情

《孔乙已》“窃书不能算偷……窃书！……读书人的事，能算偷么？

**Comment by DuLerWeil** [comment]
至少是华为员工挂以华为名义推出的项目。但是在此问题上，普通员工不敢贸然代表公司承认，能采取的措施就是能改则改、回避问题以及避重就轻。关注后续是公司出面道歉，还是临时工替罪背锅了，无奈。

**Comment by zyt12345** [comment]
KPI惹的祸

**Comment by CaoShuFeng** [comment]
华为对开源的贡献有目共睹。
至少这个东西也是开源的， 作者也在积极补救。

**Comment by choleraehyq** [comment]
Why don't you Huawei guys use go-micro/fasthttp/hystrix-go as dependencies rather than copying them into a meaningless third_party directory?

**Comment by shingtaklam1324** [comment]
@choleraehyq

What many Chinese users think is happening, including @zyt12345 and @DuLerWei is that this is not an official initiative to do this, but rather an act by an employee.

@zyt12345 's reference to KPI is talking about internal metrics in the company, so it is not completely ignorable that an employee did this to make it seem like he/she did more work.

**Comment by vbs100** [comment]
Shame on HUAWEI, requiring employees to give up holidays and work for more than TEN hours ONE day. The staff also plagiarize the code of others.

**Comment by lipengxiang1992** [comment]
Mark

**Comment by Jordanzheng** [comment]
Mark

**Comment by CaoShuFeng** [comment]
> Including a license in third_party does not account for copying the code in other places and using them as your interfaces. Where the code has been modified you must show credit to the author. I see this has since been corrected.

If all asim's comments has been addressed. And the mistake has been corrected, should we close this issue?

**Comment by xionghengheng** [comment]
被怼了。。。

**Comment by tanzhongyibidu** [comment]
mark

**Comment by zhibuzu** [comment]
m

**Comment by meggarr** [comment]
Comments from Chinese news
> 2017年6月19日在 LC3 开源峰会上，华为宣布开源了微服务框架 ServiceComb，华为称它是 FusionCloud 解决方案中 PaaS 平台的重要组成部分，内置了高可靠性运行、动态治理等运维阶段的高级能力。

Translated by Google

> June 19, 2017 At the LC3 Open Source Summit, Huawei announced ServiceComb, an open-source microservice framework. Huawei claims that it is an important part of the PaaS platform in FusionCloud. It has built-in operation and maintenance phases such as high-reliability operation and dynamic management Advanced ability.

So what do you think when you are asking `Is this an official huawei project ... ` ? @asim

**Comment by FrontMage** [comment]
This would never be a Huawei official project as long as it does any damage to the company's reputation.
It's pointless to argue, because most Chinese just do not care.
While the crowd has very short memory, this scandal would just be overwhelmed by some other gosip news.

---

If Huawei do really care, just admit it and correct it, there is no need to cover up.
Anyone would make mistakes, even Apple and Google, and they just say sorry and correct it.

**Comment by CaoShuFeng** [comment]
http://www.apache.org/foundation/license-faq.html#Distribute-changes

This document said:
>  You can give your modified code away for free, or sell it, or keep it to yourself, or whatever you like. 

So selling Apache License 2.0 licensed open source software is not illegal behavior.

It also said:
> You may distribute the result under a different license, but you need to acknowledge the use of the Foundation's software. To do otherwise would be stealing.

Redistribution without acknowledging the use of the  Foundation's software is stealing.
The license of go-micro has been included in this project. So I think the mistake has been corrected.

**Comment by asim** [comment]
I am satisfied that the authors of this library have corrected the issue by including licenses and moving code to a third party directory. I would however ask for a few things.

1. Please contribute back plugins to go-plugins to help the community benefit
2. Allow the Huawei logo to be used on the [website](https://micro.mu) to acknowledge it as a user
3. Start a discussion around a partnership to support go-micro development

**Comment by JackEggie** [comment]
feel so shame as a Chinese developer. I believe that most of us never take the _Licence_ serious, even we contribute so much code at Github.com.

We should respect more to those authors who help us to complete our work and the Open Source Community.

**Comment by leaxoy** [comment]
mark

**Comment by PerfectForNi** [comment]
Apache License 2.0 `Conditions`
- A copy of the license and copyright notice ***must be included*** with the software.
- Changes made to the code ***must be documented.***

**Comment by narry** [comment]
mark

**Comment by Viyond** [comment]
We should respect more to those authors who help us to complete our work and the Open Source Community.

**Comment by itfanr** [comment]
mark

**Comment by Leon2012** [comment]
mark

**Comment by asim** [comment]
This PR attempts to remove license references to go-micro https://github.com/ServiceComb/go-chassis/pull/151

Your works are based on go-micro, even after modification and elimination of go-micro code they are still based on it and with that you cannot remove the license. I can still point to parts of your code that look like go-micro.

**Comment by mdh67899** [comment]
mark

**Comment by eccozhou** [comment]
mark

**Comment by LiruiBryant** [comment]
mark

**Comment by bryanpkc** [comment]
PSA:  Please learn to use the Subscribe button and stop spamming people with these meaningless "mark" messages.

**Comment by winnoryder** [comment]
mark

**Comment by MondayWoo** [comment]
shame on it

**Comment by tianxiaoliang** [comment]
> http://www.apache.org/foundation/license-faq.html#Distribute-changes
> 
> This document said:
> 
> > You can give your modified code away for free, or sell it, or keep it to yourself, or whatever you like.
> 
> So selling Apache License 2.0 licensed open source software is not illegal behavior.
> 
> It also said:
> 
> > You may distribute the result under a different license, but you need to acknowledge the use of the Foundation's software. To do otherwise would be stealing.
> 
> Redistribution without acknowledging the use of the Foundation's software is stealing.
> The license of go-micro has been included in this project. So I think the mistake has been corrected.

will close this issue
