### ISSUE TITLE
服务实例异常过后缓存没有刷新，导致请求转发给异常的实例

### ISSUE THREAD

**Issue by t-xinlin** [go-chassis/go-chassis#298]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
请详细描述下，如何复现

**Comment by t-xinlin** [comment]
serviceA->mesher-mesher->serviceB
服务serviceA依赖serviceB，把serviceB停掉过

**Comment by tianxiaoliang** [comment]
mesher有本地健康检查机制 https://mesher.readthedocs.io/en/latest/configurations/health.html
会将错误的服务从注册中心中状态变为Down，A端的mesher就会在下一个时钟周期刷新本地实例了

**Comment by t-xinlin** [comment]
项目健康检查是不是有问题，打开健康检查过后看日志没反应  如果关闭健康检查的话就会出这个问题

**Comment by tianxiaoliang** [comment]
打开后会以周期进行轮训，默认是30s，确定你的portName配对

**Comment by tianxiaoliang** [comment]
mesher和 chassis的健康检查一旦并用，就会发生你说的问题了。
刚刚也定位到了根因，我们会进行修复，保证2种配置一起使用时不会引起问题

**Comment by t-xinlin** [comment]
好的 我再试试看
