### ISSUE TITLE
Any new releases in process?

### ISSUE THREAD

**Issue by crystaldust** [go-chassis/go-chassis#302]
Hi, I've been struggling with the import path and version for some time. Since the latest tag is 0.6, which still uses `github.com/ServiceComb` as the organization(refs like `github.com/ServiceComb/auth`, `github.com/ServiceComb/config`), so package management tools like `dep` or `glide` will still try to install packages under `github.com/ServiceComb`.

It should be great if we have a version tag higher than 0.6(something like 0.6.1), it's really confusing at the first time when the dependencies problems occur.

**Comment by tianxiaoliang** [comment]
good suggestion

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/releases/tag/v0.7
released
