### ISSUE TITLE
too many colons in address

### ISSUE THREAD

**Issue by Victoryship** [go-chassis/go-chassis#317]
I forward a request to a microservice through the gateway center get an error 

![image](https://user-images.githubusercontent.com/19524632/43628462-e3a89db4-972c-11e8-9af1-2381b6a53dcd.png)
and  Dashboard in the service center
![image](https://user-images.githubusercontent.com/19524632/43628510-08b83ce0-972d-11e8-8bf9-4c3ec59415bd.png)
It is normal to not directly pass the micro-service through the gateway center forwarding.

**Comment by tianxiaoliang** [comment]
what is exactly the name of this gateway center

**Comment by Victoryship** [comment]
![image](https://user-images.githubusercontent.com/19524632/43634893-12933108-9740-11e8-99d0-2c4ee68ae6b4.png)
this

**Comment by tianxiaoliang** [comment]
your server is using IPv6？

**Comment by Victoryship** [comment]
I tested it on my own machine, not on the server.

**Comment by tianxiaoliang** [comment]
Anyhow， did you machine use IPv6？

**Comment by Victoryship** [comment]
I see that this machine is enabled for IPv6. Will It use ipv6 first?

**Comment by tianxiaoliang** [comment]
your dell-pc is using java chassis?

**Comment by Victoryship** [comment]
using go chassis

**Comment by tianxiaoliang** [comment]
plz show me your dell-pc protocol related configs

**Comment by Victoryship** [comment]
Is this ip protocol?
![image](https://user-images.githubusercontent.com/19524632/43763622-c79204ce-9a5d-11e8-94dd-360729dfa277.png)

**Comment by Victoryship** [comment]
there is  login microservice 
![image](https://user-images.githubusercontent.com/19524632/43764224-7dab6e34-9a5f-11e8-9975-33a97b67e9a1.png)
there is gateway center
![image](https://user-images.githubusercontent.com/19524632/43764510-31123d7c-9a60-11e8-97ab-061c47a24a64.png)

**Comment by tianxiaoliang** [comment]
1.1.0 support ipv6, however I suggest you to use ipv4 in internal network
