### ISSUE TITLE
master 版本后，glide install 需要翻墙，不方便

### ISSUE THREAD

**Issue by capier** [go-chassis/go-chassis#318]
1、git master 版本后，glide install 需要翻墙，不方便

`
[INFO]	--> Fetching google.golang.org/genproto`
       `[WARN]	Unable to checkout google.golang.org/genproto`
      ` [ERROR]	Error looking for google.golang.org/genproto/googleapis/rpc/status: Cannot detect VCS`
      `[WARN]	Unable to set version on google.golang.org/genproto to . Err: Cannot detect VCS`
       `[INFO]	--> Fetching updates for github.com/kr/logfmt`
       `[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
`
       

2、0.6版本虽然能够glide install ,但是没法用，需要更改很多路径；bug也多

3、文档中关于  service-center的链接无效 https://github.com/go-chassis/service-center/releases 是404，请更正为  http://servicecomb.incubator.apache.org/release/

4、请问 ServiceComb Saga有没有计划出go版本？

5、华为云相关主机都开始免费试用了，但是go-chassis迟迟不能推出1.0版本，Mesher更慢，技术投入跟不上市场节奏，建议增加人员，社区的热度一时半会起不来，在观望值不值得跟进，毕竟不确信华为在go-chassis和mesher能投入多少资源！即使应用想转到华为云也不好办，

**Comment by tianxiaoliang** [comment]
关于“bug也多”这个能详细讲述下复现步骤么

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/releases/tag/v0.7 released
