### ISSUE TITLE
请问哪个模块对应 java-chassis 的archetypes ？

### ISSUE THREAD

**Issue by capier** [go-chassis/go-chassis#319]
看到 [轻松微服务系列：从一键构建微服务和DDD设计开始](http://servicecomb.incubator.apache.org/cn/docs/easy-build-microservice-system-part-I/)

请问go-chassis 有没有这样的方便工具？多谢

**Comment by tianxiaoliang** [comment]
好问题，我们没有，但是可以在以后支持脚手架生成工具

**Comment by tianxiaoliang** [comment]
a scaffold for go chassis
