### ISSUE TITLE
0.7 glide install 还是有问题

### ISSUE THREAD

**Issue by capier** [go-chassis/go-chassis#322]
> 

[INFO]	--> Fetching google.golang.org/genproto
[WARN]	Unable to checkout google.golang.org/genproto
[WARN]	Error updating google.golang.org/genproto/googleapis/rpc/status: Cannot detect VCS
[INFO]	--> Fetching updates for github.com/kr/logfmt
[ERROR]	Error scanning google.golang.org/genproto/googleapis/rpc/status: cannot find package "." in:
	/Users/capier/.glide/cache/src/https-google.golang.org-genproto/googleapis/rpc/status
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports

我在Mac 和 Ubuntu上都试装了一下，遇到以上同样的问题

**Comment by tianxiaoliang** [comment]
![image](https://user-images.githubusercontent.com/1610890/43758207-fae59fee-9a4d-11e8-81a4-1343d1004c29.png)

你需要一个可靠的代理，没办法我们在国内，又不能不用google的库吧，建议看看怎么使用代理进行glide管理

**Comment by capier** [comment]
好的，肉翻，完成安装！
如果能直接附带相应包该多好，既不用私搭vpn（国内不允许哦），购买其他的vpn不一定安全，肉翻麻烦，通过云镜像也需要一个个翻，......。

**Comment by tianxiaoliang** [comment]
we will consider about it

**Comment by marknewmail** [comment]
you can add following lines into glide.yml 
- package: google.golang.org/genproto
  version: master
  repo: https://github.com/google/go-genproto

**Comment by tianxiaoliang** [comment]
could you plz create a pull request？

**Comment by tianxiaoliang** [comment]
and if you are using highway, I suggest you use http. because highway is going to change in future
