### ISSUE TITLE
请问目前有没有项目导图？

### ISSUE THREAD

**Issue by capier** [go-chassis/go-chassis#326]
比如：（可比较清晰的认识且比较快的入手）

![0807_1](https://user-images.githubusercontent.com/27131284/43763050-3f9dc158-9a5c-11e8-80a6-417ee8bba8cc.png)

**Comment by tianxiaoliang** [comment]
there is a how it works， will that helps you？
http://go-chassis.readthedocs.io/en/latest/intro/how-it-works.html
