### ISSUE TITLE
example build error， “https://github.com/go-chassis/go-chassis/tree/master/examples/rpc/server”

### ISSUE THREAD

**Issue by wuhenfeike** [go-chassis/go-chassis#336]
# github.com/envoyproxy/go-control-plane/envoy/api/v2
github.com\envoyproxy\go-control-plane\envoy\api\v2\cds.pb.go:2226:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\cds.pb.go:2257:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\cds.pb.go:2289:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
github.com\envoyproxy\go-control-plane\envoy\api\v2\eds.pb.go:368:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\eds.pb.go:400:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
github.com\envoyproxy\go-control-plane\envoy\api\v2\lds.pb.go:474:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\lds.pb.go:506:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
github.com\envoyproxy\go-control-plane\envoy\api\v2\rds.pb.go:263:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\rds.pb.go:294:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
github.com\envoyproxy\go-control-plane\envoy\api\v2\rds.pb.go:326:13: c.cc.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
github.com\envoyproxy\go-control-plane\envoy\api\v2\rds.pb.go:326:13: too many errors

**Comment by tianxiaoliang** [comment]
plz make sure you updated glide deps

in vendor there should be grpc repo

**Comment by tianxiaoliang** [comment]
you solved problem?

**Comment by wuhenfeike** [comment]
yes， i download the old version go-control-plane-revert_grpc_version_update
