### ISSUE TITLE
variable number of argument  (a ...opt) and array (a []opt)

### ISSUE THREAD

**Issue by t-xinlin** [go-chassis/go-chassis#383]
```go
type opt func(a string)
func opt_func1(a []opt){
	log.Printf("opt_func1 a: %+v",a)
	for _,o:= range a{
		o("111")
	}
}

func opt_func2(a ...opt){
	log.Printf("opt_func2 a: %+v",a)
	for _,o:= range a{
		o("111")
	}
}

func main() {
	//a =nil
	opt_func1(nil) //print opt_func1 a: []
	opt_func2(nil) //print opt_func2 a: [nil]
}
```

goroutine 1 [running]:
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).logs(0xc000136cc0, 0xc00043eba0, 0x2, 0x2, 0x1, 0xea158c, 0x26, 0xc0001424d0, 0x1, 0x1)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:135 +0x6b
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).log(0xc000136cc0, 0x1, 0xea158c, 0x26, 0xc0001424d0, 0x1, 0x1)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:129 +0xb9
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).Info(0xc000136cc0, 0xea158c, 0x26, 0xc0001424d0, 0x1, 0x1)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:191 +0x66
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis/core/tracing.Init(0x0, 0x0)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis/core/tracing/tracer_manager.go:36 +0x7a
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis.(*chassis).initialize(0xc000182320, 0xe400000000e40760, 0x1)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis/chassis.go:168 +0x1b7
code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis.Init(0xc00013e380, 0x0)
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/vendor/github.com/go-chassis/go-chassis/chassis.go:293 +0x81
code.huawei.com/cse/mesher/server.Run()
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/server/server.go:27 +0x89
main.main()
        D:/projects/fork/CSE/mesher/src/code.huawei.com/cse/mesher/mesher.go:22 +0x20

**Comment by tianxiaoliang** [comment]
what does that code mean?
```go
type opt func(a string)
func opt_func1(a []opt){
	log.Printf("opt_func1 a: %+v",a)
	for _,o:= range a{
		o("111")
	}
}

func opt_func2(a ...opt){
	log.Printf("opt_func2 a: %+v",a)
	for _,o:= range a{
		o("111")
	}
}

func main() {
	//a =nil
	opt_func1(nil) //print opt_func1 a: []
	opt_func2(nil) //print opt_func2 a: [nil]
}
```

**Comment by t-xinlin** [comment]
vendor/github.com/go-chassis/go-chassis/core/tracing/tracer_manager.go:36
vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:135
	for _, o := range opts {
			o(opt)
	}

**Comment by tianxiaoliang** [comment]
I fix the problem, but in fact if you follow the installation guide, you won't meet this issue, always use our guide plz.
go mod is version management tool
```sh
cd go-chassis
GO111MODULE=on go mod download
#optional
GO111MODULE=on go mod vendor
```
