### ISSUE TITLE
version number is not x.x.x cause go mod can not download go-chassis as vender

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#418]
version number is not x.x.x cause go mod can not download go-chassis as vender
please use format like MAJOR.MINOR.PATCH

**Comment by tianxiaoliang** [comment]
where this error comes from

**Comment by daqingshu** [comment]
> where this error comes from

use go-chassis as mod
you can create a demo project, add go-chassis as mod
then GO111MODULE=on go mod vendor, it just can download 0.8.0 for latest, not 1.0

**Comment by tianxiaoliang** [comment]
plz check https://github.com/go-chassis/go-chassis-examples
see if you can download 1.0.1
it works in my laptop

**Comment by daqingshu** [comment]
> plz check https://github.com/go-chassis/go-chassis-examples
> see if you can download 1.0.1
> it works in my laptop

yes， version like  1.0.1  x.y.z work 
but like 1.0 x.y  does not work :)

I just means version number must like x.y.x then the go mod able to download it.
tks
