### ISSUE TITLE
我在用go-chassis里的go-hystrix熔断后还会走正常的function，再走降级的fallback function（正常应该是触发熔断后就直接fallback,除非过了时间窗口的探测），官方go-hystrix里的就是触发熔断后就不会恢复正常状态，不知道是不是bug呢

### ISSUE THREAD

**Issue by yangyunchao212** [go-chassis/go-chassis#421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
circuit open后，无法走到正常业务逻辑中，你指的走进哪段fuction

**Comment by tianxiaoliang** [comment]
fixed
