### ISSUE TITLE
method do not support: OPTIONS

### ISSUE THREAD

**Issue by eastdx** [go-chassis/go-chassis#437]
{"level":"ERROR","timestamp":"2018-11-19 22:43:48.126 +08:00","file":"go-chassis/chassis.go:206","msg":"run chassis fail:","data":{"error":"method do not support: OPTIONS"}

 能否支持OPTIONS的请求，或增加配置支持acess-cross？

在带有自定义header的场景，一定会有OPTIONS请求探测，请问有什么办法解决吗？

**Comment by tianxiaoliang** [comment]
see if you can integrate it with go-chassis
https://github.com/emicklei/go-restful/blob/master/examples/restful-options-filter.go

**Comment by daqingshu** [comment]
> see if you can integrate it with go-chassis
> https://github.com/emicklei/go-restful/blob/master/examples/restful-options-filter.go

do you means wish somebody create a Pull Request?

**Comment by tianxiaoliang** [comment]
Yes

**Comment by Rushi-Kumar** [comment]
Is there any solution of this problem, Does chassis framework expose ws container to add filter, I could not find any way to add, Please let us know if there is any solution for this

**Comment by NVIERAINFO** [comment]
func newRestfulServer(opts server.Options) server.ProtocolServer {
	ws := new(restful.WebService)
	if archaius.GetBool("servicecomb.metrics.enable", false) {
		metricPath := archaius.GetString("servicecomb.metrics.apiPath", DefaultMetricPath)
		if !strings.HasPrefix(metricPath, "/") {
			metricPath = "/" + metricPath
		}
		openlog.Info("Enabled metrics API on " + metricPath)
		ws.Route(ws.GET(metricPath).To(api.PrometheusHandleFunc))
	}
	addProfileRoutes(ws)
	con := restful.NewContainer()
	if archaius.GetBool("servicecomb.service.enableCors", false) {
		cors := restful.CrossOriginResourceSharing{
			ExposeHeaders:  []string{"X-My-Header", "*"},
			AllowedHeaders: []string{"Content-Type", "Accept", "*"},
			AllowedMethods: []string{"POST", "OPTIONS", "GET", "*"},
			CookiesAllowed: false,
			AllowedDomains: []string{"*"},
			Container:      con}
		con.Filter(cors.Filter)

		// Add container filter to respond to OPTIONS
		con.Filter(con.OPTIONSFilter)
	}
	return &restfulServer{
		opts:      opts,
		container: con,
		ws:        ws,
	}
}

**Comment by tianxiaoliang** [comment]
so great, thanks very much, but  servicecomb.service.enableCors is not good for a configuration design

plz learn about how we launch a server

https://go-chassis.readthedocs.io/en/latest/user-guides/protocols.html

cors is a concept for http server, so please support this config instead

```yaml
servicecomb:
  protocols:
    rest:
      listenAddress: 0.0.0.0:5000
      enableCORS: true
    rest-admin:
      listenAddress: 0.0.0.0:5001
    grpc:
      listenAddress: 0.0.0.0:6000
```
