### ISSUE TITLE
多协议支持

### ISSUE THREAD

**Issue by sundayslove** [go-chassis/go-chassis#440]
目前Go-chassis提供了三种协议：rest, grpc, highway。
有以下几个问题想请较一下：
1. 这三种协议是完全独立的吗？有在内部实现协议转换吗？（我目前没看到有这个功能，想确认一下）
2. 如果没有实现内部转换，一个服务提供者想提供rest和grpc两种服务，是不是就得将相同的业务逻辑按照这两种协议分别实现一次？
3. 关于协议的取舍，有什么基于经验的建议吗？网上查阅资料，貌似对外rest，对内rpc比较常见。

**Comment by tianxiaoliang** [comment]
1, 独立，无转换
2. 对
3. 协议我还是建议使用原生的http，也就是go chassis的rest，兼容性比较高，而grpc只是作为我们生态的一种扩展，go chassis才支持，但是开发体验恐怕不如http。性能上来说grpc的确要比http省资源
https://dev.to/plutov/benchmarking-grpc-and-rest-in-go-565

**Comment by sundayslove** [comment]
好的，了解了，谢谢

**Comment by tianxiaoliang** [comment]
嗯 有问题再交流
