### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by adteven** [go-chassis/go-chassis#451]
go-chassis git:(master) ✗ GO111MODULE=on go mod download
go: finding k8s.io/api v0.0.0-20180925152912-a191abe0b71e
go: finding k8s.io/api v0.0.0-20180824172530-dd5c735cbff9
go: k8s.io/api@v0.0.0-20180925152912-a191abe0b71e: git fetch -f https://github.com/kubernetes/api refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/cuiboqiang/workspace/goworkspace/pkg/mod/cache/vcs/e5dcdfe061d044413d88cabafb5d13ca80abedb39b7761f921bb5f9d23587372: exit status 128:
        error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
        fatal: The remote end hung up unexpectedly
        fatal: early EOF
        fatal: index-pack failed
go: k8s.io/api@v0.0.0-20180824172530-dd5c735cbff9: unknown revision dd5c735cbff9
go: error loading module requirements

**Comment by tianxiaoliang** [comment]
if you are in china, you need find your own way to download them through a proxy

**Comment by adteven** [comment]
i have use vpn And other dep hava download

**Comment by tianxiaoliang** [comment]
how about simply try “go get  k8s.io/api”
