### ISSUE TITLE
missing logger param

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#452]
https://github.com/go-chassis/go-chassis/blob/b4494b73a3f3f9d1493861eef6c8aeb31ec9d7a5/core/registry/bootstrap.go#L148

**Comment by tianxiaoliang** [comment]
thanks, do you wish to contribute this code?

**Comment by daqingshu** [comment]
> thanks, do you wish to contribute this code?

I have no permission push code from company.

I use go-chassis as golang microservice framework over CloudSOP and PaaS v2

**Comment by daqingshu** [comment]
> thanks, do you wish to contribute this code?

yes
