### ISSUE TITLE
是否支持自定义路由，文档没看到

### ISSUE THREAD

**Issue by zhangfeng751** [go-chassis/go-chassis#454]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/user-guides/router.html 这个是否能帮上忙

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/blob/master/examples/router/servicecomb/client/conf/router.yaml
这个例子

如果觉得我们文档需要优化 请指出，或者欢迎帮我们完善文档
