### ISSUE TITLE
fatal error: concurrent map writes for service discovery

### ISSUE THREAD

**Issue by jiangecho** [go-chassis/go-chassis#472]
```
fatal error: concurrent map writes

goroutine 116 [running]:
runtime.throw(0x10b7e63, 0x15)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0003261e8 sp=0xc0003261b8 pc=0x42c082
runtime.mapassign_faststr(0xf2c100, 0xc0006ffd70, 0x10b421f, 0x12, 0xc000964ab8)
        /usr/local/go/src/runtime/map_faststr.go:275 +0x3bf fp=0xc000326250 sp=0xc0003261e8 pc=0x41260f
github.com/go-chassis/go-chassis/core/registry.(*noIndexCache).Set(0xc00078b270, 0x10b421f, 0x12, 0xeb6080, 0xc000845960)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:37 +0x1ba fp=0xc0003262d0 sp=0xc000326250 pc=0x9ad0ba
github.com/go-chassis/go-chassis/core/registry.(*indexCache).Set(0xc000703920, 0x10b421f, 0x12, 0xeb6080, 0xc000845960)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:98 +0x5a fp=0xc000326308 sp=0xc0003262d0 pc=0x9ad8ca
github.com/go-chassis/go-chassis/core/registry.RefreshCache(0x10b421f, 0x12, 0xc00000c170, 0x1, 0x1, 0xc000326718)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/healthz.go:172 +0xb61 fp=0xc000326698 sp=0xc000326308 pc=0x9b0071
github.com/go-chassis/go-chassis/core/registry/servicecenter.filterReIndex(0xc0008458e0, 0x1, 0x4, 0x10b421f, 0x12, 0x10a9c4b, 0x7)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/servicecenter/cache.go:295 +0x4a3 fp=0xc0003267e8 sp=0xc000326698 pc=0xa8d4a3
github.com/go-chassis/go-chassis/core/registry/servicecenter.(*ServiceDiscovery).FindMicroServiceInstances(0xc00012a080, 0xc0000961e0, 0x28, 0x10b421f, 0x12, 0x0, 0x0, 0x0, 0xf1ae80, 0x203000, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/servicecenter/servicecenter.go:331 +0x6b6 fp=0xc000326978 sp=0xc0003267e8 pc=0xa94f56
github.com/go-chassis/go-chassis/core/loadbalancer.BuildStrategy(0xc0000961e0, 0x28, 0x10b421f, 0x12, 0x10a66de, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/loadbalancer/load_balancer.go:57 +0x10f fp=0xc000326af8 sp=0xc000326978 pc=0x9b993f
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).getEndpoint(0x1a37100, 0xc0009667e0, 0x10acb81, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:50 +0x1dc fp=0xc000326d30 sp=0xc000326af8 pc=0x9dc27c
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).handleWithNoRetry(0x1a37100, 0xc0007a2940, 0xc0009667e0, 0x10acb81, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:94 +0x6d fp=0xc000326de0 sp=0xc000326d30 pc=0x9dcedd
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).Handle(0x1a37100, 0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:87 +0x16c fp=0xc000326fe0 sp=0xc000326de0 pc=0x9dce5c
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc000327010 sp=0xc000326fe0 pc=0x9db288
github.com/go-chassis/go-chassis/core/handler.(*RouterHandler).Handle(0x1a37100, 0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/router_handler.go:41 +0x2f2 fp=0xc000327350 sp=0xc000327010 pc=0x9ddd62
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc000327380 sp=0xc000327350 pc=0x9db288
github.com/go-chassis/go-chassis/core/handler.(*ConsumerRateLimiterHandler).Handle(0x1a37100, 0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/qps_consumer_flow_control_handler.go:23 +0x104 fp=0xc0003274d0 sp=0xc000327380 pc=0x9dd624
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc0007a2940, 0xc0009667e0, 0xc00014ef60)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc000327500 sp=0xc0003274d0 pc=0x9db288
github.com/go-chassis/go-chassis/core.(*abstractInvoker).invoke(0xc0008342a0, 0xc0009667e0, 0xc0009667e0, 0x1)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/invoker.go:47 +0x295 fp=0xc000327578 sp=0xc000327500 pc=0xb51b15
github.com/go-chassis/go-chassis/core.(*RPCInvoker).Invoke(0xc0007e8420, 0x121ab20, 0xc0000a2018, 0x10b421f, 0x12, 0x10ba308, 0x17, 0x10b0b47, 0xf, 0x1016b60, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/rpc_invoker.go:47 +0x317 fp=0xc000327818 sp=0xc000327578 pc=0xb522c7
github.com/brocaar/loraserver/rpcCenter/client.(*UplinkClient).HandleRXPackets(0x1a36bc0, 0x600000000000000, 0x0, 0x0, 0x0, 0x19d1b9d8, 0x0, 0x0, 0x0, 0xc000806729, ...)

```

**Comment by tianxiaoliang** [comment]
which version?

**Comment by tianxiaoliang** [comment]
I checked latest code,  there is no such problem, I recommend you to upgrade to latest release

**Comment by jiangecho** [comment]
刚才升级到了最新的1.1.2，还是会出一样的问题。
是在压力比较大的情况下出现的。

**Comment by tianxiaoliang** [comment]
升级后，报错日志发下

**Comment by jiangecho** [comment]
你好，错误日志一样的

**Comment by tianxiaoliang** [comment]
压力是多大

**Comment by tianxiaoliang** [comment]
我在新代码甚至找不到
github.com/go-chassis/go-chassis/core/registry.(*noIndexCache).Set
这个方法，能给我截个图看看么

**Comment by tianxiaoliang** [comment]
core/registry/cache_index.go:37 这行代码的截图

**Comment by jiangecho** [comment]
> 我在新代码甚至找不到
> github.com/go-chassis/go-chassis/core/registry.(*noIndexCache).Set
> 这个方法，能给我截个图看看么

抱歉呀，我现在没有复现了，也找不到```github.com/go-chassis/go-chassis/core/registry.(*noIndexCache).Set
```， 另外```core/registry/cache_index.go:37 ```这行是空行，可能是哪儿搞错了。

我先把这个issue关了吧，等复现了，我重新给你们反馈，然后附上更详细的信息。

谢谢哈

**Comment by jiangecho** [comment]
@tianxiaoliang 你好，我又复现了
版本：v1.1.2
压力：每秒3000次rpc左右
备注：我们有多个微服务，但每次都是挂在同一个微服务
日志如下：

fatal error: concurrent map read and map write

goroutine 1019076 [running]:
runtime.throw(0x10e3c0d, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc064486b08 sp=0xc064486ad8 pc=0x42c3f2
runtime.mapaccess1_faststr(0xf45bc0, 0xc00074f3b0, 0x10cf444, 0x13, 0xc000307828)
        /usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc064486b78 sp=0xc064486b08 pc=0x412138
github.com/go-chassis/go-chassis/core/registry.(*IndexCache).setTagsBeforeQuery(...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:116
github.com/go-chassis/go-chassis/core/registry.(*IndexCache).Get(0xc00006e6c0, 0x10cf444, 0x13, 0xc02f77c180, 0x1, 0xc064486db8, 0xc03bd842b0, 0x1)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:87 +0x459 fp=0xc064486c10 sp=0xc064486b78 pc=0x9b1639
github.com/go-chassis/go-chassis/core/registry/servicecenter.(*ServiceDiscovery).FindMicroServiceInstances(0xc000284e00, 0xc00023aed0, 0x28, 0x10cf444, 0x13, 0x0, 0x0, 0x0, 0x203017, 0x20300b, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/servicecenter/servicecenter.go:333 +0x736 fp=0xc064486e88 sp=0xc064486c10 pc=0xa99506
github.com/go-chassis/go-chassis/core/loadbalancer.BuildStrategy(0xc00023aed0, 0x28, 0x10cf444, 0x13, 0x10c07e4, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/loadbalancer/load_balancer.go:57 +0x10f fp=0xc064487008 sp=0xc064486e88 pc=0x9bcd4f
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).getEndpoint(0x1a611b8, 0xc0649bb8c0, 0x10c6d3c, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:50 +0x1dc fp=0xc064487240 sp=0xc064487008 pc=0x9df64c
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).handleWithNoRetry(0x1a611b8, 0xc03fca6000, 0xc0649bb8c0, 0x10c6d3c, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:94 +0x6d fp=0xc0644872f0 sp=0xc064487240 pc=0x9e02ad
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).Handle(0x1a611b8, 0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:87 +0x16c fp=0xc0644874f0 sp=0xc0644872f0 pc=0x9e022c
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc064487520 sp=0xc0644874f0 pc=0x9de658
github.com/go-chassis/go-chassis/core/handler.(*RouterHandler).Handle(0x1a611b8, 0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/router_handler.go:41 +0x2f2 fp=0xc064487860 sp=0xc064487520 pc=0x9e13b2
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc064487890 sp=0xc064487860 pc=0x9de658
github.com/go-chassis/go-chassis/core/handler.(*ConsumerRateLimiterHandler).Handle(0x1a611b8, 0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/qps_consumer_flow_control_handler.go:38 +0x2ad fp=0xc064487a28 sp=0xc064487890 pc=0x9e0b9d
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc03fca6000, 0xc0649bb8c0, 0xc018eaf940)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc064487a58 sp=0xc064487a28 pc=0x9de658
github.com/go-chassis/go-chassis/core.(*abstractInvoker).invoke(0xc0337555e0, 0xc0649bb8c0, 0xc0649bb8c0, 0x1)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/invoker.go:47 +0x295 fp=0xc064487ad0 sp=0xc064487a58 pc=0xb51925
github.com/go-chassis/go-chassis/core.(*RPCInvoker).Invoke(0xc032fe0e40, 0x123a3e0, 0xc0000320c0, 0x10cf444, 0x13, 0x10def20, 0x1e, 0x10c77c8, 0xb, 0x1030660, ...)

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/releases/tag/v1.1.3

**Comment by jiangecho** [comment]
v1.1.3还是有这个问题的
