### ISSUE TITLE
我用rpc怎么启动不了啊

### ISSUE THREAD

**Issue by zgsxhcyxd** [go-chassis/go-chassis#473]
# command-line-arguments
./main.go:27:71: cannot use &ksm_srv_user.UserService_serviceDesc (type *"google.golang.org/grpc".ServiceDesc) as type *"github.com/go-chassis/vendor/google.golang.org/grpc".ServiceDesc in argument to server.WithGRPCServiceDesc

**Comment by tianxiaoliang** [comment]
你需要先了解下go语言的依赖的一些限制，其实go语言的依赖管理确实不太成熟和友好，有点反人类。我说下你遇到的问题。
你的go path下面有个google.golang.org/grpc
但是go chassis的vendor下也有个google.golang.org/grpc， 你可以简单理解为，go认为连个库是不一样的，最终导致你的报错

**Comment by zgsxhcyxd** [comment]
好的，谢谢了
