### ISSUE TITLE
提交文档bug

### ISSUE THREAD

**Issue by zgsxhcyxd** [go-chassis/go-chassis#476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zgsxhcyxd** [comment]
文档rpc示例 配置文件路径设置 CHASSIS_CONF_DIR==/path/to/conf_folder多了一个=

**Comment by tianxiaoliang** [comment]
你好，是否有兴趣帮忙修改下，就在docs目录下
