### ISSUE TITLE
GRPC性能问题

### ISSUE THREAD

**Issue by tomlee0201** [go-chassis/go-chassis#485]
你好，我们使用了grpc作为rpc的方案，在使用过程中发现GRPC的客户端和服务器端的压力差别很大。在每秒3500次请求的情况下，客户端的压力在单核cpu的100%，而服务器的压力只有30%。这是否正常？

**Comment by tianxiaoliang** [comment]
可否给出测试代码

**Comment by tianxiaoliang** [comment]
fixed, plz use new release 1.2.0
