### ISSUE TITLE
[Critical] invalid provider service address

### ISSUE THREAD

**Issue by lei-pub** [go-chassis/go-chassis#496]
After I upgrade go-chassis to v1.2.0, it use **0.0.0.0** instead of local IP address when registering provider to service center. When consumer call the provider from another node, it fails, 'cause could not find the provider locally (could not find service instance on *0.0.0.0*).

`chassis.yaml` file of provider:

> ---
> cse:
>   service:
>     registry:
>       address: http://100.109.34.225:30100
>   protocols:
>     rest:
>       listenAddress: "0.0.0.0:36001"

Test result:
![snipaste_2019-01-07_14-56-39](https://user-images.githubusercontent.com/46245845/50753412-cb79f680-128c-11e9-9c12-63ce65b288a6.png)

**Comment by lei-pub** [comment]
I made a PR to fix this issue, please review, hope it helps.
#497

**Comment by tianxiaoliang** [comment]
thanks
