### ISSUE TITLE
fatal error: concurrent map writes for service discovery

### ISSUE THREAD

**Issue by jiangecho** [go-chassis/go-chassis#500]
#472 

你好，在v1.1.3上还是有这个问题呀，日志如下：

fatal error: concurrent map read and map write

goroutine 525736 [running]:
runtime.throw(0x11b27ba, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0193dec08 sp=0xc0193debd8 pc=0x42c402
runtime.mapaccess1_faststr(0xfe2380, 0xc0000d2c90, 0x119cbe5, 0x12, 0xc000c7f708)
        /usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc0193dec78 sp=0xc0193dec08 pc=0x412138
github.com/go-chassis/go-chassis/core/registry.(*IndexCache).setTagsBeforeQuery(...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:116
github.com/go-chassis/go-chassis/core/registry.(*IndexCache).Get(0xc000198480, 0x119cbe5, 0x12, 0xc019536cf0, 0x1, 0xc0193deeb8, 0xc0194a3be0, 0x1)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/cache_index.go:87 +0x459 fp=0xc0193ded10 sp=0xc0193dec78 pc=0xa0e529
github.com/go-chassis/go-chassis/core/registry/servicecenter.(*ServiceDiscovery).FindMicroServiceInstances(0xc000140080, 0xc000264060, 0x28, 0x119cbe5, 0x12, 0x0, 0x0, 0x0, 0xc017a94ff0, 0x203006, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/registry/servicecenter/servicecenter.go:333 +0x736 fp=0xc0193def88 sp=0xc0193ded10 pc=0xb1c896
github.com/go-chassis/go-chassis/core/loadbalancer.BuildStrategy(0xc000264060, 0x28, 0x119cbe5, 0x12, 0x118d1be, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/loadbalancer/load_balancer.go:57 +0x10f fp=0xc0193df108 sp=0xc0193def88 pc=0xa19c3f
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).getEndpoint(0x1bc2408, 0xc016caa480, 0x1194484, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:50 +0x1dc fp=0xc0193df340 sp=0xc0193df108 pc=0xa3c6fc
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).handleWithNoRetry(0x1bc2408, 0xc017772e00, 0xc016caa480, 0x1194484, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:94 +0x6d fp=0xc0193df3f0 sp=0xc0193df340 pc=0xa3d35d
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).Handle(0x1bc2408, 0xc017772e00, 0xc016caa480, 0xc01629caa0)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/loadbalance_handler.go:87 +0x16c fp=0xc0193df5f0 sp=0xc0193df3f0 pc=0xa3d2dc
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc017772e00, 0xc016caa480, 0xc01629caa0)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc0193df620 sp=0xc0193df5f0 pc=0xa3b708
github.com/go-chassis/go-chassis/core/handler.(*RouterHandler).Handle(0x1bc2408, 0xc017772e00, 0xc016caa480, 0xc01629caa0)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/router_handler.go:41 +0x2f2 fp=0xc0193df960 sp=0xc0193df620 pc=0xa3e462
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc017772e00, 0xc016caa480, 0xc01629caa0)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/handler_chain.go:42 +0x78 fp=0xc0193df990 sp=0xc0193df960 pc=0xa3b708
github.com/go-chassis/go-chassis/core/handler.(*ConsumerRateLimiterHandler).Handle(0x1bc2408, 0xc017772e00, 0xc016caa480, 0xc01629caa0)
        /Users/jiangecho/go/src/github.com/go-chassis/go-chassis/core/handler/qps_consumer_flow_control_handler.go:38 +0x2ad fp=0xc0193dfb28 sp=0xc0193df990 pc=0xa3dc4d

**Comment by tianxiaoliang** [comment]
Hi，可否先看下你这笔代码是否已经修改了
https://github.com/go-chassis/go-chassis/commit/1e994caf0efe5f0f887294cb2465760465cd8c8f

···go
func routeTagToTags(t *model.RouteTag) utiltags.Tags {
	tag := utiltags.Tags{}
	if t != nil {		if t != nil {
		return utiltags.Tags{KV: t.Tags, Label: t.Label}			tag.KV = make(map[string]string, len(t.Tags))
		for k, v := range t.Tags {
			tag.KV[k] = v
		}
		tag.Label = t.Label
		return tag
	}		}
	return utiltags.Tags{}		return tag
}	}
···

**Comment by jiangecho** [comment]
你好，应当是已经修改了的，如下：

```
// routeTagToTags returns tags from a route tag
func routeTagToTags(t *model.RouteTag) utiltags.Tags {
  tag := utiltags.Tags{}
  if t != nil {
    tag.KV = make(map[string]string, len(t.Tags))
    for k, v := range t.Tags {
      tag.KV[k] = v
    }
    tag.Label = t.Label
    return tag
  }
  return tag
}
```

**Comment by jiangecho** [comment]
在高压力的情况下，很容易复现。

**Comment by jiangecho** [comment]
没有呢，我们完全没有侵入到go-chassis内部。
