### ISSUE TITLE
服务实例异常后，服务实例列表更新特别慢

### ISSUE THREAD

**Issue by tomlee0201** [go-chassis/go-chassis#506]
使用docker部署多个实例时，当使用docker stop命令停掉某个实例后，在service-center的前端上面长时间显示这个实例还存在，时间大概是2-4分钟，之后才会消失。这个期间会有一部分业务请求到这个实例上导致失败。
使用原生的程序部署，在杀掉某一个实例时，可以看见下面的日志。猜测是原生程序在捕捉到退出信号后，去反注册了自己。而docker中来不及去反注册的，我该如何尽快让服务列表更新。原生的好像也有偶尔更新比较慢的情况。
```
2019-01-15 18:04:06.196 +08:00 DEBUG servicecenter/servicecenter.go:157 unregisterMicroServiceInstance success, microServiceID/instanceID = 4d02c52f189011e9b5f61c36bbec6c65/e2abcccb18ac11e99cc91c36bbec6c65.
```

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/blob/e9ea0dff95287e58759c987ff4d39b3b06050d8d/chassis.go#L245

you can see what kind of signal chassis accepts, you can add signal here, docker stop also has signal, you can simply add to here

**Comment by tianxiaoliang** [comment]
https://xiaozhou.net/stop-docker-container-gracefully-2016-09-08.html

**Comment by tomlee0201** [comment]
非常感谢
