### ISSUE TITLE
external gateway

### ISSUE THREAD

**Issue by shaogangchen** [go-chassis/go-chassis#510]
**Is your feature request related to a problem? Please describe.**
 As the external interface of the entire microservice system, the gateway provides services to end users, accesses RESTful requests, and forwards them to internal microservices. 

**Describe the solution you'd like**
the gateway provides services to end users, accesses RESTful requests, and forwards them to internal microservices. 

**Describe alternatives you've considered**
the external system and the micro service can communication through message bus as well

**Additional context**

**Comment by tianxiaoliang** [comment]
go chassis is not going to deliver API gateway, but you can develop one based on go-chassis.

**Comment by mi4tin** [comment]
> go chassis is not going to deliver API gateway, but you can develop one based on go-chassis.

可否提供一些适合go chassis网关的解决方案

**Comment by tianxiaoliang** [comment]
基于 go chassis开发一个是最快的方案

**Comment by tianxiaoliang** [comment]
当前网关已经开发中，有mesher承载https://github.com/apache/servicecomb-mesher

**Comment by tianxiaoliang** [comment]
mesher网关已经开发完成https://mesher.readthedocs.io/en/latest/configurations/edge.html
