### ISSUE TITLE
为什么在 import "github.com/go-chassis/go-chassis" 后，代码就不能被像dlv、jetbrains golang这样的工具断点调试呢

### ISSUE THREAD

**Issue by calvinlee1** [go-chassis/go-chassis#511]
**Describe the bug**

**Version of go chassis**

**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
ide请使用go 1.9以下进行debug，这个问题是go团队引入的，并且ide并没有做适配和go chassis无关

**Comment by calvinlee1** [comment]
谢谢
