### ISSUE TITLE
请问go chassis 可以与 java chassis互相调用吗？

### ISSUE THREAD

**Issue by calvinlee1** [go-chassis/go-chassis#513]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
嗯 没问题，

1. go chassis可以调用java chassis的rest服务，

2. java chassis的rest服务可以访问go chassis的rest服务，但是go chassis得提供契约

**Comment by calvinlee1** [comment]
有相关的例子提供吗？

**Comment by tingyin** [comment]
> go chassis 调用java chassis 非常简单，你按照各自的快速开始开发即可
> 
> java 调go 我们会在近期提供demo

问一下，java调用go的例子现在哪有啊？

**Comment by modernstar** [comment]
同求java调用go服务的例子！在java-chassis中使用restTemplate post 时是失败的，抓包发现没有提交对象的序列化JSON，无法使用传统的方式调用！

**Comment by yhs0092** [comment]
https://education.huaweicloud.com:8443/courses/course-v1:HuaweiX+CBUCNXP012+Self-paced/courseware/9d1e7d073ba04f6ebc11d984dbc72eb5/9c3e1e51e02e40008f19f375f9fe95b6/
华为云的21天微服务培训课程里第13天是讲Java和go相互调用的

**Comment by wangqj** [comment]
文档请参考：https://docs.go-chassis.com/user-guides/java-call-go.html
里面有demo。
