### ISSUE TITLE
允许使用随机端口

### ISSUE THREAD

**Issue by yockii** [go-chassis/go-chassis#524]
特别是针对服务提供者，应该允许使用随机端口，同时建议改进现有的启动机制。
根据我的理解，目前的启动机制是会先主动注册服务，然后才去启动各个服务端口，尽管从某种意义上来说，消费者不需要主动启动服务监听端口，但这完全可以通过配置来实现，以表明自己是一个纯粹的消费者。
因此我觉得应该在Init时，如果非纯粹的消费者，可以立刻使用net.Listen将端口占住，如果遇到配置了端口但已被占用的情况，则启动失败，无需再与注册中心交互；这里成功后，listen实例保存到对应的协议server中供后续启动，同时获取到真实的端口提交给注册中心。
而后再在Start时，直接利用http.Server的Serve或者ServeTLS并传入之前对应的listen实例来提供服务即可。

个人觉得随机端口号作用很大，特别是单机多服务集群的情况下。如果方案有什么问题或者不合理之处请随时指出。因为本人刚接触go-chassis，对代码并不熟悉，故不直接pull-request了，希望go-chassis能真正发展成为microservice rapid framework

**Comment by tianxiaoliang** [comment]
感谢建议。

**随机端口：**
我认为你的想法很好，现在go-chassis就支持用户如果不配端口，就使用一个写死的端口，还很不灵活，使用随机端口更好点。

**启动流程**
你说的都挺好的，我只补充一个优化点，在init中注册实例时先将服务实例状态置为OUTOFSERVICE状态，这样consumer本身就没办法服务，这个状态就固定在这了，而对于provider，调用start后将实例状态更新为UP就可以了


你现在可以开始看看代码，期待你的pull request

**Comment by tianxiaoliang** [comment]
可以贡献下文档，说明随机端口如何使用 https://docs.go-chassis.com/user-guides/protocols.html

**Comment by yockii** [comment]
> 可否贡献下文档，说明随机端口如何使用 https://docs.go-chassis.com/user-guides/protocols.html

好的
