### ISSUE TITLE
同一个微服务客户端，当访问不通的http url，能路由到不同的微服务

### ISSUE THREAD

**Issue by fffmonkeyking** [go-chassis/go-chassis#526]
同一个微服务客户端，当访问不通的http url，能路由到不同的微服务：

例如：
微服务客户端：client_a
微服务1：micro_service_1（100.100.100.101:5001）
微服务2：micro_service_2（100.100.100.102:5001）

当 client_a 访问 http://MicroServer/path1 时，路由到 micro_service_1
当 client_a 访问 http://MicroServer/path2 时，路由到 micro_service_2

这个路由策略目前是否已经支持？

另外：
1、如果一个micro-service是有状态的，go-chassis是否支持client总是能将状态相关的两个request路由到相同的micro-sercice？

感谢！

**Comment by tianxiaoliang** [comment]
会话粘滞https://docs.go-chassis.com/user-guides/strategy.html

路由规则定义https://docs.go-chassis.com/user-guides/router.html

**Comment by fffmonkeyking** [comment]
感谢回复。

会话粘滞https://docs.go-chassis.com/user-guides/strategy.html
：经验证 - 配置SessionStickiness后，在微服务周期内，总访问同一个微服务

路由规则定义https://docs.go-chassis.com/user-guides/router.html
1、不能通过http url 的path 来定向路由 到指定microservice；
2、在rest编程模型下，可以通过设置match规则中的header来定向路由 到指定microservice：
    req.Header.Set("Access", "5001-A-microservice")
3、但在rpc编程模型下，怎么设置match规则中的header？

**Comment by tianxiaoliang** [comment]
grpc目前只支持除了header match的其他特性，我们会考虑后续支持，或者欢迎你提交Pull request

**Comment by fffmonkeyking** [comment]
ok.

再请教一个负载均衡相关的问题：
go-chassis文档的负载均衡一章有以下描述：
"
Load balancing
概述
用户可以通过配置选择不同的负载均衡策略，当前支持轮询、随机、基于响应时间的权值、会话保持等多种负载均衡策略。

负载均衡功能作用于客户端，且依赖注册中心。
"

描述中，说“负载均衡功能作用于客户端”：
1、这儿的这个客户端的具体定义是什么？他与传统的CS模式中的Client的含义是否一致？
2、如果要在andriod终端上实现描述中的客户端，那相关的客户端机制（比如负载均衡、服务发现、...）都要在andriod终端上重新实现一遍？
3、go-chassis是否支持：gateway这样的部署方式，即将LoadBalance这样的机制实现在Gateway上，然后客户端向gateway发送req，gateway负责完成LB和route，并返回rsp给客户端？

注：如果我的理解不正确，还请指正；
PS：大牛有其他联系方式么，方面向你进一步请教go-chassis的问题；

**Comment by tianxiaoliang** [comment]
1. google client-side load balancing
2. 安卓支持go语言的话，可以使用go-chassis，否则应用api gateway技术
3. 不支持

**Comment by fffmonkeyking** [comment]
go-chassis 支持 api gateway技术么？

**Comment by tianxiaoliang** [comment]
你可以基于他开发一个，也欢迎自行开源，回馈到社区

fffmonkeyking <notifications@github.com> 于2019年2月21日周四 下午5:45写道：

**Comment by fffmonkeyking** [comment]
我看 go-chassis的介绍里有：
“
● 插件化注册中心: 默认支持Service Center，kubernetes，istio
”

即 registry 可支持 k8s；

但我在代码里没看到对 k8s 的支持，包括example里面也没有；
gochassis的开源代码里是否已经集成对 k8s 的支持？

**Comment by tianxiaoliang** [comment]
https://docs.go-chassis.com/discovery/kube-discovery.html

fffmonkeyking <notifications@github.com> 于2019年2月22日周五 上午10:29写道：

**Comment by tianxiaoliang** [comment]
> ok.
> 
> 再请教一个负载均衡相关的问题：
> go-chassis文档的负载均衡一章有以下描述：
> "
> Load balancing
> 概述
> 用户可以通过配置选择不同的负载均衡策略，当前支持轮询、随机、基于响应时间的权值、会话保持等多种负载均衡策略。
> 
> 负载均衡功能作用于客户端，且依赖注册中心。
> "
> 
> 描述中，说“负载均衡功能作用于客户端”：
> 1、这儿的这个客户端的具体定义是什么？他与传统的CS模式中的Client的含义是否一致？
> 2、如果要在andriod终端上实现描述中的客户端，那相关的客户端机制（比如负载均衡、服务发现、...）都要在andriod终端上重新实现一遍？
> 3、go-chassis是否支持：gateway这样的部署方式，即将LoadBalance这样的机制实现在Gateway上，然后客户端向gateway发送req，gateway负责完成LB和route，并返回rsp给客户端？
> 
> 注：如果我的理解不正确，还请指正；
> PS：大牛有其他联系方式么，方面向你进一步请教go-chassis的问题；

可以加我微信tianxiaoliang2017
