### ISSUE TITLE
客户端大量TIME_WAIT，"MaxIdleConns"值的设置失败。

### ISSUE THREAD

**Issue by sundayslove** [go-chassis/go-chassis#548]
性能测试时，客户端出现大量TIME_WAIT。go-chassis启动时将 **MaxIdleConns** 置为512，但是似乎设置没成功，打印出来的值是50，见下图
![image](https://user-images.githubusercontent.com/33319673/53872712-c392c480-4039-11e9-8d5e-23d0fc59b4d1.png)

请问是什么原因呢，全局搜索，似乎也没其它地方设置了 MaxIdleConns 的值

**Comment by sundayslove** [comment]
不好意思了，按Ctrl+enter自动提交了。问题还没描述完，这里补充。

我怀疑 **MaxIdleConns** 的值设置失败，所以打印出来看了一下。截图如下：
![image](https://user-images.githubusercontent.com/33319673/53872422-2f286200-4039-11e9-82ba-3f788d5e5804.png)

**Comment by tianxiaoliang** [comment]
will fix

**Comment by tianxiaoliang** [comment]
如果你想在配置文件中控制更多的配置项，欢迎像我PR中那样贡献代码

**Comment by sundayslove** [comment]
好的
