### ISSUE TITLE
url支持模糊匹配吗？

### ISSUE THREAD

**Issue by sundayslove** [go-chassis/go-chassis#581]
注册的url支持模糊匹配吗？或者支持通配符吗？
比如我写这样一个路由规则：
[]restful.Route{
	{Method: http.MethodPost, Path: "/", ResourceFuncName: "testfunc"},
}
有办法匹配所有的请求吗。

**Comment by lizihuai** [comment]
动态路由，如：/{subpath:*} 
相关文档 ： https://github.com/emicklei/go-restful

**Comment by sundayslove** [comment]
好的，谢谢，问题已解决。
