### ISSUE TITLE
could chassis register endpoint to SC with ?sslEnabled=true suffix 

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#589]
**Is your feature request related to a problem? Please describe.**
ServiceCenter support EndpointsMap 

"rest": "1.2.3.4:8080?sslEnabled=true"

**Describe the solution you'd like**
want go-chassis support listen like 1.2.3.4:8080?sslEnabled=true or better solution 

**Describe alternatives you've considered**
first is just modify MakeEndpointMap func, like 
restful_server.Start()   if TLSConfig 1= nil then append ?sslEnabled=true

second is allow user config full schema "https://ip:port?"
in server_manager.initialServer  parse it, split host and port for server Address

maybe the first is better

**Comment by tianxiaoliang** [comment]
should use first solutin to follow java chassis mechnism

**Comment by daqingshu** [comment]
> should use first solutin to follow java chassis mechnism

 java chassis mechnism is below

support second solution  like. 
"rest://127.0.0.1:8080?sslEnabled=true&protocol=http2"

read from config file， convert to Endpoint object
https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java#L75


set listen  as URIEndpointObject 
https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/core/src/main/java/org/apache/servicecomb/core/transport/AbstractTransport.java#L147

URIEndpointObject class parse "127.0.0.1:8080?sslEnabled=true" or "rest://127.0.0.1:8080?sslEnabled=true&protocol=http2"
https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/URIEndpointObject.java#L46

**Comment by daqingshu** [comment]
> > should use first solutin to follow java chassis mechnism
> 
> java chassis mechnism is below
> 
> support second solution like.
> "rest://127.0.0.1:8080?sslEnabled=true&protocol=http2"
> 
> read from config file， convert to Endpoint object
> https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java#L75
> 
> set listen as URIEndpointObject
> https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/core/src/main/java/org/apache/servicecomb/core/transport/AbstractTransport.java#L147
> 
> URIEndpointObject class parse "127.0.0.1:8080?sslEnabled=true" or "rest://127.0.0.1:8080?sslEnabled=true&protocol=http2"
> https://github.com/apache/servicecomb-java-chassis/blob/dd685837c7fd37f818747c8f014a89d0d7f7e308/foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/URIEndpointObject.java#L46

@tianxiaoliang how about your opnion

**Comment by tianxiaoliang** [comment]
that is fine

**Comment by daqingshu** [comment]
similar #264

**Comment by tianxiaoliang** [comment]
fixed
