### ISSUE TITLE
cannot find module providing package github.com/go-chassis/go-chassis/client/grpc

### ISSUE THREAD

**Issue by daymade** [go-chassis/go-chassis#591]
**Describe the bug**

```
cannot find module providing package github.com/go-chassis/go-chassis/client/grpc
```

**Version of go chassis**
v1.4.0

**To Reproduce**
1. go get github.com/go-chassis/go-chassis-examples
2. cd $GOPATH/src/github.com/go-chassis/go-chassis-examples/grpc/bench
3. GO111MODULE=on go mod download
4. export CHASSIS_HOME=$GOPATH/src/github.com/go-chassis/go-chassis-examples/grpc/client
5. GO111MODULE=on go run main.go

**Logs**
```
~/go/src/github.com/go-chassis/go-chassis-examples/grpc/bench$ export CHASSIS_HOME=$GOPATH/src/github.com/go-chassis/go-chassis-examples/grpc/client
~/go/src/github.com/go-chassis/go-chassis-examples/grpc/bench$ GO111MODULE=on go run main.go 
go: finding github.com/go-chassis/go-chassis/client/grpc latest
go: finding github.com/go-chassis/go-chassis/client latest
build command-line-arguments: cannot load github.com/go-chassis/go-chassis/client/grpc: cannot find module providing package github.com/go-chassis/go-chassis/client/grpc
```

**Comment by daymade** [comment]
problem solved

line 13 of `/github.com/go-chassis/go-chassis-examples/grpc/bench/main.go`

```
	_ "github.com/go-chassis/go-chassis/client/grpc"
```
should be changed to 
```
	_ "github.com/go-chassis/go-chassis-protocol/client/grpc"
```

**Comment by tianxiaoliang** [comment]
thanks so much. 

I was panning to make a "Who is using" or "Know User" list

and if you are using go chassis ,would you like us to annouce your company  is using go chassis just like other repository's readme page https://github.com/ctripcorp/apollo

That will be great for us
