### ISSUE TITLE
when use SC cluster, one of SC instance down will cause go-chassis fail

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#594]
**Describe the bug**
when use SC cluster, one of SC instance down will cause go-chassis failed to communicate

**Version of go chassis**
1.4.0

**To Reproduce**
setup SC cluster with 2 instances
run go-chassis with the 2 SC addesses
then kill first instance of SC cluster
then go-chassis can not communicate with other service

**Logs**

https://github.com/go-chassis/go-chassis/blob/606d4397b419c764a94475de587aae30519f94f1/pkg/scclient/client.go#L957

**Comment by tianxiaoliang** [comment]
log plz

**Comment by daqingshu** [comment]
> log plz

I can not trans log to here
I resolve it by check every SC instance health every 5 seconds use net.DialTimeout, and record instance health status in a map
in getAddress, I ignore bad status instance

**Comment by tianxiaoliang** [comment]
could you plz fix this problem

**Comment by daqingshu** [comment]
> could you plz fix this problem
ok , after I clean my modification

**Comment by daqingshu** [comment]
> could you plz fix this problem

how about this issue ?
