### ISSUE TITLE
是否支持配置tls1.3

### ISSUE THREAD

**Issue by icyk** [go-chassis/go-chassis#601]
go1.12  有对tls1.3做部分支持。
go-chassis是否对 1.12版本做兼容，同时支持配置tls1.3 ?
或者可以通过使用tls-tris库， 对tls1.3进行支持？

**Comment by tianxiaoliang** [comment]
无法兼容低版本tls
你说的库也并非适合生产

**Comment by icyk** [comment]
是不能兼容高版本么？

**Comment by tianxiaoliang** [comment]
我们跟着go的标准库更新，现在就是1.0 1.1 1.2

**Comment by tianxiaoliang** [comment]
只需要改下 TLSVersionMap即可

**Comment by tianxiaoliang** [comment]
另外想了解下你的业务场景为何需要最新的1.3

**Comment by icyk** [comment]
https://golang.org/doc/go1.12#tls_1_3

最新的go1.12， 有对tls1.3做支持。  这部分有考虑跟进么？

**Comment by icyk** [comment]
安全上的考量， 做高强度安全协议支持。 目前是在分析

**Comment by tianxiaoliang** [comment]
如果你能说清1.3相对于1.2的改进，那么我认为go chassis绑定go1.12+也没问题

**Comment by tianxiaoliang** [comment]
会进行支持

**Comment by tianxiaoliang** [comment]
已经支持
