### ISSUE TITLE
go chassis是否可以配合其它web框架使用

### ISSUE THREAD

**Issue by mi4tin** [go-chassis/go-chassis#614]
go chassis是否可以配合其它web框架使用

**Comment by tianxiaoliang** [comment]
请举例？ 我推荐你的前台使用nodejs开发，而不是与服务耦合在一起

**Comment by mi4tin** [comment]
> 请举例？ 我推荐你的前台使用nodejs开发，而不是与服务耦合在一起

比如gin这种的

**Comment by mi4tin** [comment]
还有就是现在go chassis没有网关之类的东西。没有鉴权，ip限制之类的功能。

**Comment by tianxiaoliang** [comment]
目前没有网关组件，但可以很快基于 chassis自己做一个，go 没法跟别的go web框架混用
