### ISSUE TITLE
lager_event_listener.go ，Event方法event.Value.(string)断言问题

### ISSUE THREAD

**Issue by simagui** [go-chassis/go-chassis#633]
Event方法event.Value.(string)断言问题
\github.com\go-chassis\go-chassis\eventlistener\lager_event_listener.go 文件
断言需要 event.Value，ok:=event.Value.(string)   if !ok{error错误处理}，但是框架源码此处没有，直接将该值toupper成大写（不严谨）。event.Value定义为interface{}类型但是在panic之前我看了值是int类型。
![image](https://user-images.githubusercontent.com/46394515/59501233-ad649200-8ecd-11e9-8478-44aadf0c02f7.png)

**Comment by tianxiaoliang** [comment]
Hi，是否愿意提个PR:)

**Comment by simagui** [comment]
好的，我试试

**Comment by simagui** [comment]
提了PR需要你授权是吗？

**Comment by tianxiaoliang** [comment]
你提交PR后我会进行代码review，然后合入
