### ISSUE TITLE
熔断可否搞成同一api，每个实例互不影响

### ISSUE THREAD

**Issue by mi4tin** [go-chassis/go-chassis#635]
例如：同一服务，有2个实例，分别为实例A，实例B。当实例A的api1因为某种原因熔断，希望实例B的api1还是可以被调用

**Comment by tianxiaoliang** [comment]
你和我的想法的一致，看你是否有兴趣开发，测试，编写文档给我提交一个PR

工作量很少，我可以辅导你完成

需要少量的代码更改以及自定义配置
首先我们的断路器会关联到一个 command name，拼装规则会细化到API
https://github.com/go-chassis/go-chassis/blob/4211f60f708f88ce59f43acae097cf770a60023a/core/handler/bizkeeper_consumer_handle.go#L23

为了到达你要的效果需要拼接Endpoint，这个字段作为可选项，作为拼装的一部分

第二件事是在配置中，需要将处理链中的顺序颠倒，断路器放到负载均衡步骤之后，这样就能拿到endpoint了

**Comment by iSange** [comment]
这个issue我先认领了。

**Comment by mi4tin** [comment]
> 你和我的想法的一致，看你是否有兴趣开发，测试，编写文档给我提交一个PR
> 
> 工作量很少，我可以辅导你完成
> 
> 需要少量的代码更改以及自定义配置
> 首先我们的断路器会关联到一个 command name，拼装规则会细化到API
> https://github.com/go-chassis/go-chassis/blob/4211f60f708f88ce59f43acae097cf770a60023a/core/handler/bizkeeper_consumer_handle.go#L23
> 
> 为了到达你要的效果需要拼接Endpoint，这个字段作为可选项，作为拼装的一部分
> 
> 第二件事是在配置中，需要将处理链中的顺序颠倒，断路器放到负载均衡步骤之后，这样就能拿到endpoint了

提了

**Comment by iSange** [comment]
这个同学已经做了，那我就不做了。等正式合入，我测试下。。
