### ISSUE TITLE
提交文档bug

### ISSUE THREAD

**Issue by laijiawei** [go-chassis/go-chassis#639]
docs/user-guides/fault-tolerance.md
这个文档里面两个参数
backoff.MinMs
backoff.MaxMs
在代码中按照下面读取
type BackoffStrategy struct {
	Kind  string `yaml:"kind"`
	MinMs int    `yaml:"minMs"`
	MaxMs int    `yaml:"maxMs"`
}
应该修改下文档，小写字母开头。

**Comment by tianxiaoliang** [comment]
好的，感谢
https://github.com/go-chassis/go-chassis/tree/master/docs
这里是文档如何在本地运行的指导，你是否愿意为我贡献这个文档修改

**Comment by laijiawei** [comment]
好的，我来改。

**Comment by tianxiaoliang** [comment]
你好，请问还愿意参与社区贡献这份文档么
