### ISSUE TITLE
如何unregister一个实例

### ISSUE THREAD

**Issue by SoldierProgrammer** [go-chassis/go-chassis#642]
当前go-chassis默认会根据心跳拉起实例，即使主动unregister后，待一定时间后又会被心跳拉起一个新实例，这对于有些服务来说并不适合。因为有些服务的实例已经不能服务了，但是在Service Center的状态还是可用状态。
例如：
一个服务，启动后向Service Center注册，启动了一个实例。但是这个服务依赖系统底层一些功能来提供服务（例如网卡等），当这个服务检测到网卡异常时，需要向Service Center通知将原有启动的实例删除（或者状态修改为不可用），待检测到网卡可用后，还需要重新启动实例。

不知道当前go-chassis有没有办法实现？或者能在unregister后能够提供取消心跳的接口，让service center不感知此实例。待此实例检测到自己可以提供服务后，再向service center重新发送心跳

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/blob/06043510a0c0e0170fbe5e00535491d63729379d/core/registry/registrator.go#L56

可以调用这个接口更新状态

**Comment by SoldierProgrammer** [comment]
update我试过，但是没有效果，不知道是不是版本问题，我用的go-chassis是1.2.7，service center是2.2.65
func UpdateSelfInstances(status string) error {
	fmt.Println("begin update instance to ", status)

	microserviceIDs := registry.SelfInstancesCache.Items()
	fmt.Println("microserviceIDs: ", microserviceIDs)
	for mid := range microserviceIDs {
		value, ok := registry.SelfInstancesCache.Get(mid)
		if !ok {
			lager.Logger.Warnf("updateSelfInstances() get SelfInstancesCache failed, mid: %s", mid)
			fmt.Println("updateSelfInstances() get SelfInstancesCache failed, mid: ", mid)
		}

		instanceIDs, ok := value.([]string)
		if !ok {
			lager.Logger.Warnf("updateSelfInstances() type asserts failed, mid: %s", mid)
			fmt.Println("updateSelfInstances() type asserts failed, mid: ", mid)
		}

		fmt.Println("instanceIDs are: ")
		fmt.Println(instanceIDs)

		for _, iid := range instanceIDs {
			err := registry.DefaultRegistrator.UpdateMicroServiceInstanceStatus(mid, iid, status)
			if err != nil {
				lager.Logger.Errorf(err, "updateSelfInstances() failed, mid/iid/status: %s/%s/status", mid, iid, status)
				fmt.Println("updateSelfInstances() failed, mid/iid/status: ", mid, iid, status)
				return err
			}
		}
	}

	return nil
}

**Comment by tianxiaoliang** [comment]
status与固定常量的，我们只会保留UP状态的服务，更新后30秒就会生效，你查下sc的状态常量，我记得有个OUT_OF_SERVICE和DOWN，另外建议你更新到最新版本试试

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/blob/06043510a0c0e0170fbe5e00535491d63729379d/core/registry/servicecenter/cache.go#L280

**Comment by SoldierProgrammer** [comment]
没有找到OUT_OF_SERVICE和DOWN，只看到有这么两个状态
	DefaultStatus     = "UP"
	TESTINGStatus     = "TESTING"

**Comment by SoldierProgrammer** [comment]
runtime.go里面倒是有个：
//Status
const (
	StatusRunning = "UP"
	StatusDown    = "DOWN"
)

我调用update接口时传的是“DOWN”

**Comment by tianxiaoliang** [comment]
https://github.com/apache/servicecomb-service-center/blob/ae14fbf3e6568b558b33435847bafe3682060d72/server/core/swagger/v4.yaml#L1305

建议升级试试
