### ISSUE TITLE
Is the current log system unable to implement remote note

### ISSUE THREAD

**Issue by mi4tin** [go-chassis/go-chassis#646]

**Comment by tianxiaoliang** [comment]
这是什么问题?

**Comment by mi4tin** [comment]
就是现在是不是只能写本地日志，不能接入邮件，短信通知

**Comment by tianxiaoliang** [comment]
如果你有这种需求，那么并不是由日志模块提供，而是由告警模块提供的，我可以定义API，是否愿意编写实现？

**Comment by mi4tin** [comment]
可以

**Comment by tianxiaoliang** [comment]
告警其实分几种做法

一种是logstash这样的agent去收集本地日志上传到一个服务，服务可以配置告警规则并对接短信，邮件等系统

一种是进程直接通知邮件或者短信，这种方式其实不好，没有中间管理，其实这些告警记录不好追踪

你确定要用第二种方法？而不是使用logstash的生态去做？

**Comment by mi4tin** [comment]
哦，那用第一种吧
