### ISSUE TITLE
一个微服务对外服务的监听地址和端口可以多个吗

### ISSUE THREAD

**Issue by SoldierProgrammer** [go-chassis/go-chassis#648]
chassis.yaml中
cse:
  protocols:
    rest:
      listenAddress: 127.0.0.1:8080

这个listenAddress是否可以配置多个，同时每个配置对应不同的路由规则？
例如127.0.0.1:8080  对应路由  /path/deal1
       127.0.0.1:8081  对应路由  /path/deal2

如果可以的话，怎么配置？？

**Comment by mi4tin** [comment]
一个微服务，应该只有一个地址。你能说下你的用意吗

**Comment by iSange** [comment]
rest 这个配置8080
rest-test 这个配置8081
应该就可以达到你想要的想过，  用 - 分隔符 第一位是协议第二位随便写。

**Comment by mi4tin** [comment]
个人觉得，可以开成2个微服务

**Comment by tianxiaoliang** [comment]
没有2个微服务的概念，是一个微服务进程有多个端口
完整例子，欢迎写个文章帮我们宣传下
https://github.com/go-chassis/go-chassis/tree/master/examples/mutiports

**Comment by tianxiaoliang** [comment]
一个服务可能包含一个业务能力的API，还有个给内部运维使用的管理台API，为了面对这种场景而开发的多端口特性。

**Comment by SoldierProgrammer** [comment]
Thanks all
