### ISSUE TITLE
rest请求问题

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#649]
问题1 ：https://github.com/go-chassis/go-chassis/tree/master/examples/rest
用这个样例client找不到服务
![image](https://user-images.githubusercontent.com/37329665/60648485-9ed91d00-9e72-11e9-8891-abbf907be202.png)
问题2 ：不用服务中心直接调用的时候，client端应该怎么配置，可以方便提供样例代码吗

**Comment by tianxiaoliang** [comment]
req, err := rest.NewRequest("GET", "http://RESTServer/sayhello/world", nil)

这个里面的地址你怎么填写的

**Comment by tianxiaoliang** [comment]
无需配置中心的配置的例子在这里，重点是disable服务中心
https://github.com/go-chassis/go-chassis/blob/master/examples/communication/

https://github.com/go-chassis/go-chassis/blob/master/examples/communication/server/conf/chassis.yaml

**Comment by xiejunshi** [comment]
地址是req, err := rest.NewRequest("GET", "http://127.0.0.1:5001/sayhello/world", nil)

**Comment by tianxiaoliang** [comment]
你跑rest例子，就必须用服务名，你可以对比下rest和commucation2个代码和配置的区别，不要更改默认代码和配置是能跑起来的

xiejunshi <notifications@github.com> 于2019年7月5日周五 下午3:44写道：

**Comment by xiejunshi** [comment]
知道了 谢谢了
