### ISSUE TITLE
goland debug错误

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#651]
![image](https://user-images.githubusercontent.com/37329665/60706376-e7a8d880-9f3b-11e9-8353-417cbf3ade74.png)
在使用微服务的时候debug报错
GOSDK是1.11.11
dlv.exe是用的goland-2018.3.2自带的
备注：不使用go-chassis的时候debug普通的代码不会报错

**Comment by tianxiaoliang** [comment]
需要使用go 1.11的命令行和1.9的IDE
compiler，这个错误是go官方引入的，只要使用cgo的工程都无法使用debug，他们会在未来版本修复

xiejunshi <notifications@github.com> 于2019年7月5日周五 下午3:48写道：
