### ISSUE TITLE
Is there an error retry mechanism for a request?

### ISSUE THREAD

**Issue by hjdo** [go-chassis/go-chassis#653]
Hi, I checked [this document](https://docs.go-chassis.com/user-guides/fault-tolerance.html), but i have a few questions:

- What kind of error will trigger the retry mechanism?
- Can I customize the type of error that triggers a retry? for example: HTTP request returns not 200

**Comment by tianxiaoliang** [comment]
https://docs.go-chassis.com/user-guides/transport.html

**Comment by hjdo** [comment]
thank you, this is what i want.
