### ISSUE TITLE
下载的例子有没有，和java-chassis混合开发，java的网关，下总是报错

### ISSUE THREAD

**Issue by Gold-Z** [go-chassis/go-chassis#654]
主要是想实现动态下载zip压缩包

**Comment by tianxiaoliang** [comment]
java的网关是指edge service？它不支持go chassis，除非你再go chassis这边提供一个契约，可以看下这个例子，照着做就可以通，但下载例子我们不提供

https://github.com/go-chassis/go-chassis-examples/tree/master/java-call-go

**Comment by tianxiaoliang** [comment]
https://mesher.readthedocs.io/en/latest/configurations/edge.html 另外还是推荐你用mesher网关，易用性高
