### ISSUE TITLE
求助goland调试问题

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#670]
debug报错
![image](https://user-images.githubusercontent.com/37329665/61843288-b33a9380-aecd-11e9-8707-0c5de26cd042.png)

**Comment by lizihuai** [comment]
https://github.com/go-chassis/go-chassis/issues/651 参考一下这里

**Comment by xiejunshi** [comment]
好像不一样，我这个截图里面div.exe的路径配置有问题，不知道在哪里修改
