### ISSUE TITLE
请问日志怎么配置，可以按size和时间同时打包吗

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#676]
![image](https://user-images.githubusercontent.com/37329665/62359698-e9b98380-b549-11e9-98a0-9c4d1f73ae84.png)

**Comment by tianxiaoliang** [comment]
是的，策略中，大小的优先级最高，一旦达到这个大小就会打包，过了一天就会按天打包

**Comment by xiejunshi** [comment]
但是我看这个是重启就会打包重新打一个包啊

**Comment by xiejunshi** [comment]
我想让它重启不打包 可以吗
