### ISSUE TITLE
use zap for logging

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#685]
**Is your feature request related to a problem? Please describe.**
want  better performance logger

**Describe the solution you'd like**
use https://github.com/uber-go/zap for the logger

**Comment by daqingshu** [comment]
ref https://github.com/apache/servicecomb-service-center/blob/master/pkg/log/zap.go

**Comment by tianxiaoliang** [comment]
当前耦合度太高了，各个项目都在用openlogging，所以不会替换了
