### ISSUE TITLE
grpc 的各种选项 option 支持吗？ 

### ISSUE THREAD

**Issue by abserari** [go-chassis/go-chassis#689]
没有看到 grpc-go 在哪。只是支持了 grpc-go 的 protoc 生成的 ServiceDesc 吗？

**Comment by tianxiaoliang** [comment]
当前没有投入研发力量在这里，你是否有兴趣给我们贡献代码以支持options

**Comment by yhyddr** [comment]
现在还了解不多，暂时无从下手

**Comment by tianxiaoliang** [comment]
可以先看先运行起来感受下，看看是否适合自己的场景
