### ISSUE TITLE
日志打包问题

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#692]
现在的日志会在项目重启的时候打包，可用修复一下这个问题吗，感觉不是很合理

**Comment by tianxiaoliang** [comment]
我也觉得不合理，可以提个PR修复这个问题么

**Comment by tianxiaoliang** [comment]
v2.0.3已发布并解决这个问题https://go-chassis.readthedocs.io/en/latest/user-guides/log.html
