### ISSUE TITLE
对接到istio只能支持rest协议吗

### ISSUE THREAD

**Issue by wksw** [go-chassis/go-chassis#693]
**Describe the bug**
按照“https://github.com/go-chassis/go-chassis-examples/tree/master/pilot-v2”这个例子对接istio，我的一个服务是grpc一个是rest， 我用rest的服务去请求grpc服务时报“lb: No available instance for protocol server [grpc] , microservice: auth-microservice has map[rest:172.20.1.153:8080]”

**Version of go chassis**
1.6.0
**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
不应当有这样的限制，可能是个bug（比如写死），你是否愿意fix下。只要能对接到k8s的service就能拿到port name，name根据port name来换算协议即可，比如 port name叫grpc,rest,grpc-admin.rest-legacy都可以支持，只要符合{protocol}-{surfix}
