### ISSUE TITLE
如何通过长连接进行文件传输

### ISSUE THREAD

**Issue by xiejunshi** [go-chassis/go-chassis#694]
https://github.com/go-chassis/go-chassis/tree/master/examples/fileupload

我看这个例子是一次性读取文件到内存里面然后再发送请求，我想运用长连接的方式，读一点发一点，以此来减少程序的运行内存，请问要怎么操作。
ps: 顺便咨询一下为什么我使用channel来存储任务队列，但是任务执行完之后内存并不能很快的释放。可以顺便解惑吗，谢谢了

**Comment by tianxiaoliang** [comment]
只能给你提示这不属于框架工作范畴

提示：http truncate
