### ISSUE TITLE
consumer send request fail when provider graceful shutdown

### ISSUE THREAD

**Issue by zhangjvvv** [go-chassis/go-chassis#710]
**Describe the bug**
https://github.com/go-chassis/go-chassis/blob/ed5cf65ee44675cb3e98e37298b8edb112871a18/chassis.go#L258

After `server.Shutdown` , before `UnRegistrySelfInstances `, consumer can also send new request but it will fail.
why not  `UnRegistrySelfInstances ` first ?
**Version of go chassis**
1.4.0

**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
的确是更加正确的做法，只是客户端需要watch sc的变化，否则还是有30秒的缓存过期时间，这期间会向server发出请求，你是否愿意提个PR？
