### ISSUE TITLE
请问有go-chassis框架的性能测试数据吗？

### ISSUE THREAD

**Issue by xdjakiechen** [go-chassis/go-chassis#721]

**Comment by tianxiaoliang** [comment]
性能是测试过，也经常进行性能调优，但是还是希望你自行进行benchmark，机器不同，业务代码不同，性能千差万别。

这是bench工具
https://github.com/go-chassis/go-chassis-bench


如果你想问相对原生http损耗多少。
性能损耗最大的是客户端（也就是上面的bench mark工具），服务端的性能相对原生http服务不会损耗多少
