### ISSUE TITLE
go-chassis是否支持ws？支持时间表如何？

### ISSUE THREAD

**Issue by nginxpre** [go-chassis/go-chassis#732]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
希望你可以跟我们一起共同设计，然后合入到主干

**Comment by tianxiaoliang** [comment]
考虑到ws并不能纳入到治理能力中，所以不接纳该需求，使用该go chassis并不会组织你使用websocket，两者不是互斥的
