### ISSUE TITLE
go-chassis支持按照api流控特性的发布时间点是什么时候？

### ISSUE THREAD

**Issue by nginxpre** [go-chassis/go-chassis#733]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
明年Q2

**Comment by fansno** [comment]
有设计吗？是不是可以参考熔断 区分API的机制?

**Comment by tianxiaoliang** [comment]
#881 正在合入

**Comment by tianxiaoliang** [comment]
已经支持，请参考最新的限流文档
