### ISSUE TITLE
go-chassis和mesher目前对接的配置中心是否还是公有云CC，还未对接ServiceComb-kie？

### ISSUE THREAD

**Issue by nginxpre** [go-chassis/go-chassis#738]
**Describe the bug**

**Version of go chassis**

**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
https://github.com/apache/servicecomb-kie/tree/master/client/adaptor
已经对接了，文档稍后补充

**Comment by zhulijian1** [comment]
已支持ServiceComb-kie
https://go-chassis.readthedocs.io/en/latest/control-plane/servicecomb.html#servicecomb-kie

**Comment by tianxiaoliang** [comment]
欢迎使用
