### ISSUE TITLE
mesher功能几个疑问

### ISSUE THREAD

**Issue by nginxpre** [go-chassis/go-chassis#753]
1.为什么没有把edge对api的映射转换通过增强router功能搞定？这样路由策略是不是更为灵活？
2.熔断如果是实例或实例-api粒度的，必须放在loadbalance之后，这样就没办法隔离故障实例，只能降级了

**Comment by tianxiaoliang** [comment]
1. router是客户端的能力，edge的api映射是服务端能力
2. 你理解的降级是什么

**Comment by nginxpre** [comment]
降级就是当被调用服务吞吐量巨大，资源不够用等情况时关掉强制返回错误，以避免雪崩效应。但是我们针对instance或instance-api级别的熔断，必须放在loadbalance之后，那么如果出现某个实例故障的情况时，就会出现失败率很高，此时无法隔离这个故障实例，只能强制返回失败

**Comment by tianxiaoliang** [comment]
所以lb里有个重试功能，对于错误调用可以重新select一个实例访问
