### ISSUE TITLE
v1.8.1版本首次启动程序后CSE没有schema信息

### ISSUE THREAD

**Issue by zhulijian1** [go-chassis/go-chassis#782]
**Describe the bug**

使用v1.8.1版本第一次启动程序后CSE schema界面没有schema信息，但是停止进程并第二次启动后（此时schema目录下已经有第一次启动时自动生成的yaml文件了）能注册上。另外v1.7.6版本没有这个问题

**Version of go chassis**

v1.8.1

**To Reproduce**

1. 本地运行CSE
2. 编写程序，go.mod引用github.com/go-chassis/go-chassis v1.8.1
3. 运行程序
4. Service Center界面查询schema信息

**Logs**

第一次启动时日志中没有出现"AddSchemas success"，第二次启动时才出现

**Comment by tianxiaoliang** [comment]
ok 提个PR修复下吧
