### ISSUE TITLE
go注册契约，为何会把不带json关键字的字段也注册到契约中？

### ISSUE THREAD

**Issue by h00379108** [go-chassis/go-chassis#811]
ype CreateThumbnailRequest struct {
common.Common
TenantID string json:"tenant_id,omitempty"
}

type Common struct {
InputURI string json:"input_file_addr"
InputType int32 json:"input_type" // not used until now, not implemented in pb
OutputURI string json:"output_file_addr,omitempty"
Priority int32 json:"priority,omitempty"
NotifyURL string json:"notify_url,omitempty"
NotifyServerDomain string json:"notify_domain_name,omitempty"
OutFilenames []string json:"output_filenames,omitempty"
Auth httpx.Auth
}

注册的契约显示为：
{
"Common": {
"Auth": {
"ak": "string",
"sk": "string",
"token": "string"
},
"input_file_addr": "string",
"input_type": 0,
"notify_domain_name": "string",
"notify_url": "string",
"output_file_addr": "string",
"output_filenames": [
"string"
],
"priority": 0
},
"tenant_id": "string"
}

期望不要把common写到契约，期望是：
{
"input_file_addr": "string",
"input_type": 0,
"notify_domain_name": "string",
"notify_url": "string",
"output_file_addr": "string",
"output_filenames": [
"string"
],
"priority": 0,
"tenant_id": "string"
}

毕竟postman的请求也是不带common的：
{"projectId":"3a3b9aa89c49465ba71f029004964d1f","priority":0,"input_type":1,"output_file_addr":"s3://ziqiantest/test/","tar":1,"input_file_addr":"s3://ziqiantest/test/test.mp4"}

**Comment by tianxiaoliang** [comment]
代码是从开源的go-restful社区folk过来的，那边的能力肯定是一致的，并没有规划在这个上边做太多的能力，如果有兴趣，可以提个PR到go-restful的库中

**Comment by tianxiaoliang** [comment]
目前的规避方式是，专门写用来生成文档的struct
