### ISSUE TITLE
负载均衡存在数据竞态

### ISSUE THREAD

**Issue by michale-developer** [go-chassis/go-chassis#821]
WARNING: DATA RACE

Read at 0x000002aaaa20 by goroutine 55:
  github.com/go-chassis/go-chassis/pkg/scclient.RoundRobin.func1()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/load_balance.go:25 +0xaf
  github.com/go-chassis/go-chassis/pkg/scclient.(*AddressPool).GetAvailableAddress()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/pool.go:65 +0x350
  github.com/go-chassis/go-chassis/pkg/scclient.(*RegistryClient).formatURL()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/client.go:959 +0x6c
  github.com/go-chassis/go-chassis/pkg/scclient.(*RegistryClient).Heartbeat()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/client.go:741 +0x1ee
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*Registrator).Heartbeat()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/servicecenter.go:97 +0x9f
  github.com/go-chassis/go-chassis/core/registry.(*HeartbeatService).DoHeartBeat()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/heartbeat.go:44 +0x8a
  github.com/go-chassis/go-chassis/core/registry.(*HeartbeatService).run()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/heartbeat.go:54 +0xa5
  github.com/go-chassis/go-chassis/core/registry.(*HeartbeatService).Start()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/heartbeat.go:34 +0x4b

Previous write at 0x000002aaaa20 by goroutine 37:
  github.com/go-chassis/go-chassis/pkg/scclient.RoundRobin.func1()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/load_balance.go:26 +0x13b
  github.com/go-chassis/go-chassis/pkg/scclient.(*AddressPool).GetAvailableAddress()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/pool.go:65 +0x350
  github.com/go-chassis/go-chassis/pkg/scclient.(*RegistryClient).formatURL()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/client.go:959 +0x6c
  github.com/go-chassis/go-chassis/pkg/scclient.(*RegistryClient).BatchFindInstances()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/pkg/scclient/client.go:523 +0x2f8
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*CacheManager).pullMicroServiceInstance()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/cache.go:216 +0x10f
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*CacheManager).refreshCache()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/cache.go:73 +0x79
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*CacheManager).AutoSync.func1()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/cache.go:60 +0x7d

Goroutine 55 (running) created at:
  github.com/go-chassis/go-chassis/core/registry.DoRegister()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/registrator.go:196 +0x11e
  github.com/go-chassis/go-chassis.Run()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/chassis_api.go:74 +0x8d
  main.main()
{"level":"DEBUG","timestamp":"2020-03-26 16:39:31.193 +08:00","file":"servicecenter/servicecenter.go:106","msg":"heartbeat success, microServiceID/instanceID: 5d49bc39231b3ffabb10d63479c98154d7ca991d/3e00e0586f3d11ea801f0242ac120008."}
      /go/src/gateway/main.go:32 +0xa03  【启动 chassis.Run()】

Goroutine 37 (running) created at:
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*CacheManager).AutoSync()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/cache.go:58 +0x1b5
  github.com/go-chassis/go-chassis/core/registry/servicecenter.(*ServiceDiscovery).AutoSync()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/servicecenter/servicecenter.go:318 +0x97
  github.com/go-chassis/go-chassis/core/registry.enableServiceDiscovery()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/discovery.go:78 +0x2cf
  github.com/go-chassis/go-chassis/core/registry.Enable()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/core/registry/registrator.go:160 +0x37e
  github.com/go-chassis/go-chassis.(*chassis).initialize()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/chassis_init.go:125 +0x684
  github.com/go-chassis/go-chassis.Init()
      /go/pkg/mod/github.com/go-chassis/go-chassis@v1.8.2/chassis_api.go:137 +0xe4
  main.main()
      /go/src/gateway/main.go:27 +0x9bd 【初始化 chassis.Init()】

**Comment by tianxiaoliang** [comment]
感谢，会解决

**Comment by ichiro999** [comment]
请问你使用的版本是哪个，描述下测试场景

**Comment by michale-developer** [comment]
> 请问你使用的版本是哪个，描述下测试场景

使用版本v1.8.2，开启竞态编译后提示的错误.

**Comment by ichiro999** [comment]
#822 已经提交pr，可以review一下

**Comment by tianxiaoliang** [comment]
fixed
