### ISSUE TITLE
go-chassis中如何配置健康检查，并且registerSchema(serverName string, structPtr interface{}, opts ...server.RegisterOption)都是什么意思

### ISSUE THREAD

**Issue by jarry-jiehu** [go-chassis/go-chassis#833]
**Describe the bug**

**Version of go chassis**

**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
业务的健康需要用户自己实现rest api 比如访问/health 进行一次健康检查

registerSchema是用来注册业务逻辑的
