### ISSUE TITLE
服务注册到cse，只能在shema中看到一类API接口，比如rest或rest-elb

### ISSUE THREAD

**Issue by Fang57** [go-chassis/go-chassis#835]
protocols:
    rest-elb:
      listenAddress: 127.0.0.1:9988
      advertiseAddress:   127.0.0.1:9988
    rest:
      listenAddress:  127.0.0.1:8081
      advertiseAddress:   127.0.0.1:8081
注册中心看到的（服务生成的shema，只会看到其中一种接口，）

**Comment by tianxiaoliang** [comment]
在本地生成文档时，按照端口名分开成2个文件，这样go chassis就会自动将文件上传上去。

你只需要处理生成部分
