### ISSUE TITLE
ctrl-c 无法退出进程

### ISSUE THREAD

**Issue by xy-github-issue** [go-chassis/go-chassis#845]
由于 go-chassis 捕获了 SIGINT/SIGHUP/SIGTERM 等一系列的信号，导致应用程序收到这些信号不再像期待一样地退出了。

v1.8.3

**To Reproduce**
运行 go-chassis/examples/rest/server/main.go
ctrl-c 无法退出

期望这里可以关闭捕获这几个信号的行为，如果需要维持兼容，那提供一个配置开关。
信号处理由业务来做,  go-chassis 提供一个 GracefulStop 的 api (业务自己只做一个信号处理函数，在处理完这些信号，自己退出)。

或者有其他建议吗？（现状不改的话）我考虑另一种做法是，业务也捕获这些信号，之后 sleep 一段时间再os.Exit 强行退出，感觉并不是一个很好的方案，毕竟该多久呢？

**Comment by tianxiaoliang** [comment]
嗯 这个主意不错， “go-chassis 提供一个 GracefulStop 的 api (业务自己只做一个信号处理函数，在处理完这些信号，自己退出)。”

你可以提交PR

**Comment by ZongWeiZhu** [comment]
https://github.com/go-chassis/go-chassis/pull/846

**Comment by ZongWeiZhu** [comment]
增加GracefulStop api
