### ISSUE TITLE
调用的微服务IP不存在，且每次调用都是不同的IP

### ISSUE THREAD

**Issue by panyaowei** [go-chassis/go-chassis#848]
微服务是容器化部署，注册到cse中。
微服务A访问微服务B，得到是一个不存在的IP ，每次访问都是不同的IP
报错信息：
   dial tcp 172.16.0.117:31001: connect: no route to host

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/pull/846

最近正好有个PR提到这个问题，go chassis本来优雅停机就是强制执行的，所以会将实例注销，这样客户端在下一个刷新周期时会把本地实例缓存删除掉，默认周期时30s内，如果30s内确实会出现这个问题。可以配置重试策略来规避
