### ISSUE TITLE
go1.4不能正常go get github.com/go-chassis/go-chassis v2.0.0-alpha.2+incompatible

### ISSUE THREAD

**Issue by fangwendong** [go-chassis/go-chassis#856]
go1.2正常go get但是go1.4不行，希望升级个正常的版本

**Comment by tianxiaoliang** [comment]
有报错信息么

**Comment by fangwendong** [comment]
go: git.garena.com/shopee/bg-logistics/go/chassis@v0.0.8 requires
	github.com/go-chassis/go-chassis@v2.0.0-alpha.2+incompatible/go.mod: verifying module: github.com/go-chassis/go-chassis@v2.0.0-alpha.2+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/go-chassis/go-chassis@v2.0.0-alpha.2+incompatible: 410 Gone
	server response: not found: github.com/go-chassis/go-chassis@v2.0.0-alpha.2+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

**Comment by tianxiaoliang** [comment]
执行 go get github.com/go-chassis/go-chassis 可否

**Comment by fangwendong** [comment]
我们这边有个库引用的是 2.0.0-alpha.2+incompatible

**Comment by tianxiaoliang** [comment]
可以用这个伪版本号github.com/go-chassis/go-chassis v0.0.0-20200505090058-f61a697f667a
