### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by daixiang0** [go-chassis/go-chassis#857]
**Describe the bug**

The [link ](https://join.slack.com/t/go-chassis/shared_invite/enQtMzk0MzAyMjEzNzEyLTRjOWE3NzNmN2IzOGZhMzZkZDFjODM1MDc5ZWI0YjcxYjM1ODNkY2RkNmIxZDdlOWI3NmQ0MTg3NzBkNGExZGU)in README is broken.

Also, there is no doc about how to connect.

**Comment by tianxiaoliang** [comment]
will update

**Comment by tianxiaoliang** [comment]
fow now you can add my wechat tianxiaoliang2017

**Comment by daixiang0** [comment]
It is not a good chat tool except one to one.
