### ISSUE TITLE
支持的注册中心太局限了，现在python 调用grpc不能走服务发现

### ISSUE THREAD

**Issue by Han-Ya-Jun** [go-chassis/go-chassis#880]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianxiaoliang** [comment]
请详细的描述下你面临的问题

**Comment by Han-Ya-Jun** [comment]
现在python调用chassis的grpc服务时，发现并不能走注册中心，好像是目前没有servicecomb-service-center的python客户端

**Comment by tianxiaoliang** [comment]
提供了service mesh的接入方式https://github.com/apache/servicecomb-mesher

**Comment by tianxiaoliang** [comment]
关联https://github.com/apache/servicecomb-service-center/issues/680

建议轻量的解决方案是，通过python client，接入到grpc for python的lb扩展组件中，从service center拉服务拓扑信息，并在负载均衡中进行select

**Comment by tianxiaoliang** [comment]
基于上述方案，这并非go chassis的范畴，请跟踪apache/servicecomb-service-center#680

**Comment by Han-Ya-Jun** [comment]
好的，非常感谢
