### ISSUE TITLE
paas lager和openlogging的api提供的不合理，使用者调用也不合理

### ISSUE THREAD

**Issue by tianxiaoliang** [go-chassis/go-chassis#889]
目前几个弊端

1. 充斥大量以f为结尾的调用，导致无论静态检查还是IDE都无法检查出参数数量不匹配问题，这导致错误信息丢失和错乱，致命问题
2. 包名有些过长openlogging

**Comment by yankooo** [comment]
golangci-lint 可以检查出参数个数不匹配啊，为什么检查不出来

**Comment by tianxiaoliang** [comment]
> golangci-lint 可以检查出参数个数不匹配啊，为什么检查不出来

如果能检查出来就会检查出问题了，但是之前一直都是不报错的，再改成fmt后就报参数匹配不上的问题了，IDE同理
