### ISSUE TITLE
滚动日志的时候，拷贝日志文件，以及压缩功能会造成日志丢失。

### ISSUE THREAD

**Issue by yankooo** [go-chassis/go-chassis#899]
**Is your feature request related to a problem? Please describe.**
当日志滚动的时候，先拷贝日志再清空源日志文件，可能存在丢日志的风险，配置日志文件的大小有上限50m，建议提高一点。

**Describe the solution you'd like**
也许可以做一个日志开关，可以控制这种日志滚动的行为（可以关闭），或者直接可以让用户定义Logger变量，如果不为nil，go-chassis就不初始化。

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/user-guides/log.html 看下最新的文档，适配即可

**Comment by tianxiaoliang** [comment]
50m的大小上限可以提高，这个数字请提交PR
