### ISSUE TITLE
生态：支持gin作为server插件，允许用户接入原生gin代码

### ISSUE THREAD

**Issue by tianxiaoliang** [go-chassis/go-chassis#903]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daqingshu** [comment]
ref https://gitee.com/daqingshu/go-chassis-gin
first can run version, but don't support plugin

**Comment by tianxiaoliang** [comment]
很棒，可以合入到go-chassis-extension中

**Comment by daqingshu** [comment]
please review https://github.com/go-chassis/go-chassis-extension/pull/20

**Comment by tianxiaoliang** [comment]
感谢 @daqingshu 对社区的贡献
