### ISSUE TITLE
开启TLS认证，是否可以开放设置ServerName，用于校验证书CN，而不仅仅基于域名和IP的映射关系？

### ISSUE THREAD

**Issue by rogge-zheng** [go-chassis/go-chassis#909]
在与CCE配合使用过程中，CCE容器IP是动态的，无法配置域名与IP的映射关系，会导致开启HTTPS证书认证后出现域名与IP不匹配的证书校验错误。

**Comment by tianxiaoliang** [comment]
这个是你在配置证书时做的操作，看下你的证书怎么跳过校验

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/pull/912
已经有人贡献
