### ISSUE TITLE
about kubernetes

### ISSUE THREAD

**Issue by zyjblockchain** [go-chassis/go-chassis#923]
目前我们的服务是部署在kubernetes 上，我看到 go-chassis 是有提供k8s 的插件库来支持微服务部署到kubernetes，想请问一下，go-chassis 支持k8s 是无侵入式的吗

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis-extension/tree/master/registry/kubernetes

这是k8s插架目前适配go chassis1.8.3

如果可以的话，请帮忙编译下go chassis 2.0.4的适配，可能没有工作量，我还未验证。

另外k8s的注册发现可能会在生产中遇到问题，比较适合startup的业务，后面可以视业务运行而定，按需使用service center

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/control-plane/kube-discovery.html#import-path 文档

**Comment by tianxiaoliang** [comment]
如果是非侵入式，你说的是服务网格，默认不支持k8s，但是可以自己编译出包，类似趣头条的实践。
https://github.com/apache/servicecomb-mesher/blob/master/cmd/mesher/mesher.go

代码成本也不高，改下main.go

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/user-guides/invoker.html 这里讲述了另一种支持方法，不需要注册中心，跳过客户端负载均衡，直接进行网络调用

**Comment by tianxiaoliang** [comment]
先关闭本issue，有进一步交流可以加我的微信tianxiaoliang2017
