### ISSUE TITLE
Typo: Registry 是否开启的文档中，disabled 定义解释有误

### ISSUE THREAD

**Issue by yoo-bit** [go-chassis/go-chassis#945]
**Describe the bug**
https://go-chassis.readthedocs.io/en/latest/user-guides/registry.html

配置里的 servicecomb.registry.disabled 文档中解释为: 是否 `开启` 服务注册发现模块

应为: 是否 `关闭` 服务注册发现模块，这样默认的false意思为默认开启发现

**Version of go chassis**
2.0+
**To Reproduce**
**Logs**

**Comment by tianxiaoliang** [comment]
感谢指出，是否愿意提交下这个修复

**Comment by yoo-bit** [comment]
Submitted pull request. Please check, thanks! #946

**Comment by tianxiaoliang** [comment]
Thanks for that
