### ISSUE TITLE
go-chassis文档Write rest service，样例代码错误

### ISSUE THREAD

**Issue by deernewman** [go-chassis/go-chassis#952]
**Describe the bug**
go-chassis文档Write rest service，样例代码错误
[]rf.RouteSpec报错，最新版本需要修改为[]rf.Route
![image](https://user-images.githubusercontent.com/18545928/103991659-f675e880-51cd-11eb-9d05-9fc190acd9a9.png)

2.Write your url patterns

func (r *RestFulHello) URLPatterns() []rf.Route {
    return []rf.RouteSpec{
        {Method: http.MethodGet, Path: "/sayhello/{userid}", 
         ResourceFunc: r.SayHello,
         Returns: []*rf.Returns{{Code: 200}}},
    }
}

**Version of go chassis**
latest
**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
已修复，https://go-chassis.readthedocs.io/en/latest/getstarted/writing-rest.html
