### ISSUE TITLE
v2版本是不是没有grpc，没有看到相应的examples

### ISSUE THREAD

**Issue by xtay315** [go-chassis/go-chassis#953]
v2版本是不是没有grpc，没有看到相应的examples

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis-extension/tree/master/protocol/grpc

可以看下go mod，只需要坐下简单的路径更改来适配，是否愿意贡献下

**Comment by xtay315** [comment]
准备直接放到go-chassis里还是修改 go-chassis-extension

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis-extension/tree/master/protocol/grpc 已经适配2.1.0
