### ISSUE TITLE
conf目录注入故障，导致启动失败

### ISSUE THREAD

**Issue by Reese1995** [go-chassis/go-chassis#957]
**Describe the bug**
故障注入测试：在conf目录下创建一个root权限的目录，会导致启动失败

**Version of go chassis**
v1.8.2

**To Reproduce**

**Logs**
报错位置：loader.go：LoadSchema(path string) error 
chassis_init.go:106:failed to initialize conf:  lstat {路径}/conf/test/schema: permission denied

**Comment by tianxiaoliang** [comment]
现在扫描都会尝试文件上传，你改成扫描失败跳过即可，打印warn日志，不return error

**Comment by Reese1995** [comment]
感谢快速响应！！
