### ISSUE TITLE
go-chassis 处理web请求

### ISSUE THREAD

**Issue by Pangzhihong** [go-chassis/go-chassis#973]
go-chassis处理web请求是怎么样的，和beego有什么差异？或者说go-chassis和beego有什么关联吗？

**Comment by tianxiaoliang** [comment]
类似 https://github.com/go-chassis/go-chassis-extension/tree/master/protocol/gin4r 这个插件，beego和chassis之间的差距就是可以成为一种rest server插件。现在肯定是没这个插件。可以模仿gin的接入，将beego接入

**Comment by Pangzhihong** [comment]
> 类似 https://github.com/go-chassis/go-chassis-extension/tree/master/protocol/gin4r 这个插件，beego和chassis之间的差距就是可以成为一种rest server插件。现在肯定是没这个插件。可以模仿gin的接入，将beego接入

我看有些文章说 ，”go-chassis服务端的请求是beego来处理的“ ，这个说法是正确的吗？

**Comment by tianxiaoliang** [comment]
没看过，在哪，这个不正确
