### ISSUE TITLE
TLS配置 Consumer配置是否支持通配

### ISSUE THREAD

**Issue by fanjiang-2021** [go-chassis/go-chassis#979]
消费端访问不同的提供端,需要配置各自的证书私钥,在同一个项目下,往往各个微服务使用的是同一套证书,是否有通配功能,只需要配置一处就可以,而不是每个提供端都配置,这样配置文件有点冗余

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/user-guides/tls.html

server name不填写就是全局的配置了

**Comment by five111** [comment]
> https://go-chassis.readthedocs.io/en/latest/user-guides/tls.html
> 
> server name不填写就是全局的配置了

这个是指的provider吧 consumer貌似不支持

**Comment by five111** [comment]
> 可以支持rest.Consumer.xxx: xx
> 
> 这样的配置，默认就读这个来加载client的tls配置
> 
> 可否贡献这个特性

我们正在准备做这个事情    想法与您说的类似，想以rest.Consumer.xxx: xx 为默认配置
同时我们发现一个问题，当我们将consumer端的配置做成这样后，若当前服务同时配置provider和consumer时，会有key冲突
如下图
![image](https://user-images.githubusercontent.com/19482564/121664232-da0e0d00-cad9-11eb-9266-89ffa7cdf32d.png)
所以开了 这个 https://github.com/go-chassis/go-chassis/issues/984 issue来询问这个问题
