### ISSUE TITLE
yaml配置文件是否必须存在，如果是如何加载CSE之类的环境变量

### ISSUE THREAD

**Issue by vaptu** [go-chassis/go-chassis#980]
使用ServiceStage部署go-chassis组件事，默认加载的CAS_* PAAS_*类的环境变量如何直接加载。

追踪框架代码，是必须存在`chassis.yaml`与`microservice.yaml`文件，那如何进行容器化呢

**Comment by tianxiaoliang** [comment]
请加下微信tianxiaoliang2017，深度交流下场景

**Comment by tianxiaoliang** [comment]
增加了一个额外的环境变量说明
