### ISSUE TITLE
疑惑 阅读官方文档中关于tls配置的描述中有一个配置疑问

### ISSUE THREAD

**Issue by five111** [go-chassis/go-chassis#984]
![image](https://user-images.githubusercontent.com/19482564/121648346-fe61ed80-cac9-11eb-8014-c7269ac2c544.png)
https://go-chassis.readthedocs.io/en/latest/user-guides/tls.html
文档中描述consumer的证书配置项中有一项是 TLSService.rest.Provider.verifyPeer: true
不明白的是这边为何会在consumer的配置中出现provider字样 请问是否是文档错误，如果不是，这个配置项是什么意思 该如何使用

**Comment by tianxiaoliang** [comment]
TLSService 确实是provider的名字，意思是这个服务被访问时，需要配置这些tls config

**Comment by five111** [comment]
不知这样理解是否正确 “当前服务作为consumer去访问TLSService时  若 TLSService.rest.Provider.verifyPeer 配置为true 则需要相关的tls config 否则 则不需要”
相应的 在服务作为provider取配置tls config时
![image](https://user-images.githubusercontent.com/19482564/121657519-0d00d280-cad3-11eb-8576-10dcce00fe8c.png)
这里的rest.Provider.verifyPeer: true 这个配置也可以简单理解为服务端使用证书文件校验客户端请求的开关

**Comment by tianxiaoliang** [comment]
第一个图的意思是，该服务访问tlsservice的时候需要服务端认证（mutual tls）

第二个图的意思是，该服务进行使用http协议通信的化，他访问任何服务端时，都要进行服务端认证（mutual tls）

**Comment by five111** [comment]
> 第二个图的意思是，该服务使用http协议通信的话，他访问任何服务端时，都要进行服务端认证（mutual tls）
这句话我不是很理解 这个配置是当前服务作为provider 即服务端时的配置，按您的说法 这个配置是他去访问别人的时候生效，这是他不是作为consumer即客户端吗？

**Comment by fanjiang-2021** [comment]
> 第一个图的意思是，该服务使用http协议访问tlsservice的时候需要服务端认证（mutual tls）
> 
> 第二个图的意思是，该服务使用http协议通信的话，他访问任何服务端时，都要进行服务端认证（mutual tls）

=================================================================
对于第一个图有一个疑问? 
作为消费端,采用https协议调用提供端,消费端作为客户端他可以控制自己是否校验服务端的证书是可以接受理解的,但是按照图上所配置,客户端可以设置服务端对客户端证书的校验行为,这种是否不属于安全要求,因为双向认证,服务端是否校验客户端是由服务端自己决定的

**Comment by tianxiaoliang** [comment]
我看错了

第一个图红框的内容，本来就不支持这样的配置，红框外的说的是该服务作为consumer使用http协议访问tlsservice的时候需要服务端认证（mutual tls）

第二个图的意思是，该服务作为provider，使用http协议通信的话，任何访问他的时候，都要进行客户端认证（mutual tls）
