### ISSUE TITLE
如何缩短与服务中心的健康检查时间

### ISSUE THREAD

**Issue by chenchanglong1997** [go-chassis/go-chassis#986]
需要什么配置能缩短微服务与服务中心的健康检查时间和次数

**Comment by chenchanglong1997** [comment]
本地健康检查有没有实现rest api的样例

**Comment by tianxiaoliang** [comment]
你说的是心跳？还是注册中心服务端主动检查实例health接口？

**Comment by chenchanglong1997** [comment]
> 本地健康检查有没有实现rest api的样例



> 你说的是心跳？还是注册中心服务端主动检查实例健康接口？

注册中心服务端主动检查实例健康接口,主要想服务异常，尽快从服务中心下线

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/blob/master/docs/user-guides/registry.md 可以看下这个指南
