### ISSUE TITLE
服务中心如果开启rbac则无法像java版一样注册，header没有token

### ISSUE THREAD

**Issue by cooperong** [go-chassis/go-chassis#989]
**Describe the bug**
我使用kie打开了服务中心注册，且服务中心开启了rbac，则kie无法正常注册进服务中心，因为http header缺少token，java版
可以通过yaml加入
  credentials:
    rbac:
      enabled: true
    account:
      name:    #服务中心支持的用户名
      password:   #用户名对应的密码
    cipher: default #账号密码加解密用的算法实现类
自动支持服务中心rbac注册，但kie使用的go-chassis无法支持，已在参数文件内加入以上配置，仍提示header 不含token

**Version of go chassis**

**To Reproduce**

**Logs**

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/v2.6.0/user-guides/registry.html 最新版本已经支持
