### ISSUE TITLE
chassis.yaml ssl配置读取总是不全

### ISSUE THREAD

**Issue by five111** [go-chassis/go-chassis#991]
**Describe the bug**
当我在chassisyaml中配置了ssl节点，配置如下
![配置](https://user-images.githubusercontent.com/19482564/125723067-c3e3a6a6-14f0-488e-b07a-3cd46c87b382.png)
而我启动程序时每次加载的配置却不全
![image](https://user-images.githubusercontent.com/19482564/125723450-f0733d41-5de8-4263-859a-8b90403626bd.png)

**Version of go chassis**
2.1.1
**To Reproduce**
在chassis.yaml中配置
**Logs**
{"level":"ERROR","timestamp":"2021-07-15 11:14:31.018 +08:00","file":"server/server_manager.go:64","msg":"servers failed to start, err read key file  failed"}
{"level":"ERROR","timestamp":"2021-07-15 11:14:31.018 +08:00","file":"go-chassis/chassis_api.go:103","msg":"run chassis failed:can not start [http] server,read key file  failed"}
{"level":"FATAL","timestamp":"2021-07-15 11:14:31.018 +08:00","file":"server/server.go:65","msg":"Chassis failed: can not start [http] server,read key file  failed","data":{"trace":"goroutine 1 [running]:\ngithub.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).logs(0xc00003afc0, 0xc000092d80, 0x2, 0x2, 0x4, 0xc000036730, 0x41, 0xc0005162f0, 0x1, 0x1)\n\tD:/developtools/GoPath/pkg/mod/github.com/go-chassis/seclog@v1.3.0/third_party/forked/cloudfoundry/lager/logger.go:148 +0x1f0\ngithub.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).log(0xc00003afc0, 0x4, 0xc000036730, 0x41, 0xc0005162f0, 0x1, 0x1)\n\tD:/developtools/GoPath/pkg/mod/github.com/go-chassis/seclog@v1.3.0/third_party/forked/cloudfoundry/lager/logger.go:136 +0xf9\ngithub.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).Fatal(0xc00003afc0, 0xc000036730, 0x41, 0xc0005162f0, 0x1, 0x1)\n\tD:/developtools/GoPath/pkg/mod/github.com/go-chassis/seclog@v1.3.0/third_party/forked/cloudfoundry/lager/logger.go:210 +0x6d\ngithub.com/go-chassis/openlog.Fatal(0xc000036730, 0x41, 0xc0005162f0, 0x1, 0x1)\n\tD:/developtools/GoPath/pkg/mod/github.com/go-chassis/openlog@v1.1.2/openlog.go:30 +0xdc\ngithub.com/apache/servicecomb-mesher/proxy/server.Run()\n\tD:/code/CSE/servicecomb-mesher/proxy/server/server.go:65 +0x77c\nmain.main()\n\tD:/code/CSE/servicecomb-mesher/cmd/mesher/mesher.go:47 +0x27\n"}}

**Comment by five111** [comment]
目前怀疑是Archaius这个组件在读取配置文件的时候发生了错误 但还不够清晰 @tianxiaoliang

**Comment by five111** [comment]
似乎是yaml配置值布尔类型引起的问题

**Comment by tianxiaoliang** [comment]
是的目前archaius在支持list型配置后，似乎有个bug产生了，但是没有人找到根因和修复方法https://github.com/go-chassis/go-archaius/issues/122

**Comment by five111** [comment]
chassis.go 中定义了ssl 的类型为
![image](https://user-images.githubusercontent.com/19482564/126031963-02f805f2-bc84-4720-a003-7f121dcafdac.png)
而go-archaius在读取yaml赋值的过程中会去判断即将赋值的类型 和读取值的类型，这里 ssl的值的类型为string，而读取到的值的类型为bool，类型不匹配 
go-chassis/go-archaius#113 这个PR合入之前在类型不匹配时会尝试做一次转换，而合入之后不会转换，直接退出了循环
